"""Dataset loading for the stereo-lidar-perception project.

This module is the *data* stage of the pipeline. It loads raw sensor data,
calibration and labels through the unified ``py123d`` Scene API and assembles
them into a per-frame :class:`StereoSample`, which is then handed to the
*preprocessing* module (not implemented here).

Because everything goes through :class:`py123d.api.SceneAPI`, the same code
works for any py123d dataset (Argoverse 2, nuPlan, nuScenes, Waymo, ...).
Switching datasets only changes the :class:`~py123d.api.SceneFilter` and the
root paths; the stereo-specific assembly assumes a left/right camera pair whose
ids are configurable (AV2's ``pcam_stereo_l`` / ``pcam_stereo_r`` by default).

============================ INPUTS ============================
Read from disk (paths resolved from environment variables, see
:func:`configure_dataset_paths` and ``py123d-docs/installation.md``):

* Converted py123d logs (Arrow) under ``$PY123D_DATA_ROOT/logs`` — ego state,
  camera/lidar tables, 3D box labels, sync table.
* Original sensor blobs under e.g. ``$AV2_DATA_ROOT/sensor`` — the JPEG images
  and lidar feathers (AV2 conversion stores only relative paths to these).
* Precomputed sparse depth maps under
  ``$PY123D_DATA_ROOT/preprocessed/depth_maps/<log>/<iteration>.npz`` (key
  ``depth_map``): LiDAR projected into the left stereo image. Optional — frames
  load ``None`` when a depth file is absent.
* A :class:`~py123d.api.SceneFilter` selecting dataset / split / scenes.

============================ OUTPUTS ===========================
One :class:`StereoSample` per frame (consumed by the preprocessing module):

* ``image_left`` / ``image_right`` — stereo RGB pair, ``(H, W, 3)`` uint8.
* ``depth_left`` — precomputed sparse metric depth in the left image,
  ``(H, W)`` float32 (0 = no LiDAR return), or ``None`` if not available.
* ``lidar_xyz`` — full point cloud ``(P, 3)`` in the **ego** frame;
  ``lidar_features`` — dict of per-point channels (intensity, channel,
  timestamps, ...).
* ``boxes_3d`` — ground-truth 3D boxes, ``(N, 10)`` in the **global** frame
  (``BoundingBoxSE3Index``: x,y,z,qw,qx,qy,qz,length,width,height), plus
  ``boxes_3d_labels`` / ``boxes_3d_track_tokens`` / ``boxes_3d_velocity``.
* ``boxes_2d_left`` — image-plane 2D boxes auto-generated by projecting the 3D
  boxes into the left camera, ``(M, 4)`` xyxy (clipped to the image), with
  ``boxes_2d_left_box_indices`` mapping each back to its row in ``boxes_3d``.
* ``points_outside_boxes_xyz`` — 3D positions (ego frame) of LiDAR returns that
  fall outside *every* 3D box (static/background geometry), plus the
  ``points_in_box_mask`` over ``lidar_xyz``.
* ``calibration`` — :class:`Calibration` with the left/right intrinsics, the
  camera->ego and ego->global extrinsics, and the stereo baseline.

Quick start::

    from data import Py123dDataset
    dataset = Py123dDataset(split_names=["av2-sensor_val"])
    sample = dataset[0].to_stereo_sample()   # -> StereoSample for preprocessing
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterator, List, Optional, Sequence, Union

import numpy as np

from py123d.api import SceneAPI, SceneFilter, get_filtered_scenes
from py123d.common.runtime import DatasetPaths, setup_dataset_paths
from py123d.datatypes.detections import BoxDetectionsSE3
from py123d.datatypes.sensors import Camera, CameraID, Lidar, LidarID
from py123d.datatypes.time import Timestamp
from py123d.datatypes.vehicle_state import EgoStateSE3
from py123d.geometry.transform import rel_to_abs_points_3d_array
from py123d.geometry.utils.bounding_box_utils import (
    bbse3_array_to_corners_array,
    points_3d_in_bbse3_array,
)

# Repo-local fallback: ``data/`` holds the converted ``logs/``, the original
# ``sensor/`` blobs, and ``preprocessed/`` outputs, so it can serve as every
# root at once.
DEFAULT_DATA_ROOT = Path(__file__).resolve().parent / "data"

# Default stereo pair (Argoverse 2). Override for other datasets.
DEFAULT_LEFT_CAMERA = "pcam_stereo_l"
DEFAULT_RIGHT_CAMERA = "pcam_stereo_r"

# Per-dataset "original data root" env vars. py123d derives each dataset's
# sensor root from these (e.g. AV2_DATA_ROOT -> ``<root>/sensor``).
_DATASET_ROOT_ENV_VARS: Sequence[str] = (
    "AV2_DATA_ROOT",
    "NUPLAN_DATA_ROOT",
    "WOD_PERCEPTION_DATA_ROOT",
    "WOD_MOTION_DATA_ROOT",
    "PANDASET_DATA_ROOT",
    "KITTI360_DATA_ROOT",
    "NUSCENES_DATA_ROOT",
)

CameraIdLike = Union[CameraID, str, int]
LidarIdLike = Union[LidarID, str, int]


def configure_dataset_paths(data_root: Optional[Union[str, Path]] = None) -> Path:
    """Point py123d at the dataset roots and return the resolved data root.

    The data root is taken from (in order): the ``data_root`` argument, the
    ``PY123D_DATA_ROOT`` environment variable, or :data:`DEFAULT_DATA_ROOT`.

    Any already-exported dataset root variable (``AV2_DATA_ROOT`` etc.) is left
    untouched; the rest default to ``data_root`` so the self-contained repo
    layout works out of the box while real installs keep their own paths.

    Must be called before any scene/sensor data is read, because the readers
    look up sensor locations through the process-global dataset paths. It is
    invoked automatically by :class:`Py123dDataset`.
    """
    resolved = Path(data_root or os.environ.get("PY123D_DATA_ROOT") or DEFAULT_DATA_ROOT).resolve()

    os.environ["PY123D_DATA_ROOT"] = str(resolved)
    for env_var in _DATASET_ROOT_ENV_VARS:
        # ``setdefault`` keeps user-provided roots; only fills in the gaps.
        os.environ.setdefault(env_var, str(resolved))

    # Initialise the process-global paths from the (now-populated) environment.
    setup_dataset_paths(DatasetPaths.from_env())
    return resolved


# --------------------------------------------------------------------------- #
# Geometry helpers
# --------------------------------------------------------------------------- #
def _pose_to_matrix(pose) -> np.ndarray:
    """Convert a py123d ``PoseSE3`` to a 4x4 homogeneous transform."""
    matrix = np.eye(4, dtype=np.float64)
    matrix[:3, :3] = np.asarray(pose.rotation_matrix, dtype=np.float64)
    matrix[:3, 3] = np.asarray(pose.array, dtype=np.float64)[:3]
    return matrix


def _intrinsics_matrix(intrinsics) -> np.ndarray:
    """Build a 3x3 camera matrix from py123d ``PinholeIntrinsics`` (fx,fy,cx,cy,skew)."""
    values = np.asarray(intrinsics, dtype=np.float64).ravel()
    fx, fy, cx, cy = values[0], values[1], values[2], values[3]
    skew = values[4] if values.size > 4 else 0.0
    return np.array([[fx, skew, cx], [0.0, fy, cy], [0.0, 0.0, 1.0]], dtype=np.float64)


def _boxes_to_array(boxes: Optional[BoxDetectionsSE3]) -> np.ndarray:
    """Stack box poses+dims into ``(N, 10)`` (``BoundingBoxSE3Index``), global frame."""
    if boxes is None or not boxes.box_detections:
        return np.zeros((0, 10), dtype=np.float64)
    return np.stack([d.bounding_box_se3.array for d in boxes.box_detections]).astype(np.float64)


def _project_boxes_2d(camera: Camera, boxes_array: np.ndarray):
    """Project 3D boxes into an image and return clipped amodal 2D boxes.

    :return: ``(boxes_2d, box_indices)`` where ``boxes_2d`` is ``(M, 4)`` xyxy in
        pixels (clipped to the image) and ``box_indices`` maps each 2D box to its
        row in ``boxes_array``. Boxes with no corner in front of the camera are
        dropped.
    """
    if boxes_array.shape[0] == 0:
        return np.zeros((0, 4), dtype=np.float64), np.zeros((0,), dtype=np.int64)

    corners_global = bbse3_array_to_corners_array(boxes_array).reshape(-1, 3)  # (N*8, 3)
    pixels, in_fov, depth = camera.project_points_global(corners_global)
    pixels = pixels.reshape(-1, 8, 2)
    in_fov = in_fov.reshape(-1, 8)
    in_front = depth.reshape(-1, 8) > 0.0

    width, height = camera.metadata.width, camera.metadata.height
    boxes_2d: List[np.ndarray] = []
    indices: List[int] = []
    for i in range(boxes_array.shape[0]):
        front = in_front[i]
        if not front.any() or not in_fov[i].any():
            continue
        # Amodal extent from the corners that are in front of the camera.
        corner_px = pixels[i][front]
        x_min, y_min = corner_px.min(axis=0)
        x_max, y_max = corner_px.max(axis=0)
        boxes_2d.append(
            np.array(
                [
                    np.clip(x_min, 0, width),
                    np.clip(y_min, 0, height),
                    np.clip(x_max, 0, width),
                    np.clip(y_max, 0, height),
                ],
                dtype=np.float64,
            )
        )
        indices.append(i)

    if not boxes_2d:
        return np.zeros((0, 4), dtype=np.float64), np.zeros((0,), dtype=np.int64)
    return np.stack(boxes_2d), np.asarray(indices, dtype=np.int64)


# --------------------------------------------------------------------------- #
# Output containers
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class Calibration:
    """Camera intrinsics + extrinsics for the stereo pair (SI units, metres)."""

    left_intrinsics: np.ndarray  # (3, 3)
    right_intrinsics: np.ndarray  # (3, 3)
    left_to_ego: np.ndarray  # (4, 4) camera -> ego/imu
    right_to_ego: np.ndarray  # (4, 4)
    ego_to_global: np.ndarray  # (4, 4) ego/imu -> global
    left_to_global: np.ndarray  # (4, 4)
    right_to_global: np.ndarray  # (4, 4)
    stereo_baseline_m: float
    left_is_distorted: bool
    right_is_distorted: bool


@dataclass(frozen=True)
class StereoSample:
    """All per-frame outputs handed to the preprocessing module.

    See the module docstring for field semantics. Frames/datasets without a
    given modality leave the corresponding field empty (``None`` or a
    zero-length array), so consumers can stay dataset-agnostic.
    """

    # identity
    dataset: str
    log_name: str
    scene_index: int
    iteration: int
    timestamp_us: int

    # raw stereo + lidar
    image_left: np.ndarray
    image_right: np.ndarray
    lidar_xyz: np.ndarray
    lidar_features: Optional[Dict[str, np.ndarray]]  # e.g. intensity, channel, timestamps

    # precomputed sparse depth (left image), may be None
    depth_left: Optional[np.ndarray]

    # 3D labels (global frame)
    boxes_3d: np.ndarray
    boxes_3d_labels: List[str]
    boxes_3d_track_tokens: List[str]
    boxes_3d_velocity: np.ndarray

    # 2D labels (left image, auto-generated from 3D)
    boxes_2d_left: np.ndarray
    boxes_2d_left_box_indices: np.ndarray

    # 3D positions of returns outside every box (ego frame) + membership mask
    points_outside_boxes_xyz: np.ndarray
    points_in_box_mask: np.ndarray

    # calibration
    calibration: Calibration

    def __repr__(self) -> str:
        return (
            f"StereoSample(dataset={self.dataset!r}, log={self.log_name!r}, "
            f"iter={self.iteration}, boxes_3d={len(self.boxes_3d)}, "
            f"boxes_2d={len(self.boxes_2d_left)}, lidar_pts={len(self.lidar_xyz)}, "
            f"depth={'yes' if self.depth_left is not None else 'no'})"
        )


@dataclass(frozen=True)
class Frame:
    """A single synchronized time step within a scene.

    Provides dataset-agnostic lazy accessors for individual modalities
    (:meth:`camera`, :meth:`lidar`, :meth:`boxes`, :meth:`ego_state`,
    :meth:`depth`) and the project-level :meth:`to_stereo_sample`, which bundles
    them into a :class:`StereoSample`.
    """

    scene: SceneAPI
    scene_index: int
    iteration: int
    depth_root: Optional[Path] = None

    # -- identity / metadata -------------------------------------------------
    @property
    def dataset(self) -> str:
        return self.scene.dataset

    @property
    def split(self) -> str:
        return self.scene.split

    @property
    def location(self) -> str:
        return self.scene.location

    @property
    def log_name(self) -> str:
        return self.scene.log_name

    @property
    def scene_uuid(self) -> str:
        return self.scene.scene_uuid

    @property
    def timestamp(self) -> Timestamp:
        return self.scene.get_timestamp_at_iteration(self.iteration)

    @property
    def available_camera_ids(self) -> List[CameraID]:
        return self.scene.available_camera_ids

    @property
    def available_lidar_ids(self) -> List[LidarID]:
        return self.scene.available_lidar_ids

    # -- modality accessors --------------------------------------------------
    def camera(self, camera_id: CameraIdLike) -> Optional[Camera]:
        """Return the :class:`Camera` (image + intrinsics/extrinsics) for ``camera_id``."""
        return self.scene.get_camera_at_iteration(self.iteration, camera_id)

    def cameras(self, camera_ids: Optional[Sequence[CameraIdLike]] = None) -> Dict[CameraID, Camera]:
        """Return ``{CameraID: Camera}`` for the requested (or all available) cameras."""
        ids = list(camera_ids) if camera_ids is not None else self.available_camera_ids
        out: Dict[CameraID, Camera] = {}
        for cid in ids:
            camera = self.camera(cid)
            if camera is not None:
                out[CameraID.from_arbitrary(cid)] = camera
        return out

    def lidar(self, lidar_id: Optional[LidarIdLike] = None) -> Optional[Lidar]:
        """Return a :class:`Lidar` point cloud.

        Defaults to the merged point cloud when present, otherwise the first
        available lidar, so callers need not know each dataset's lidar layout.
        """
        if lidar_id is None:
            lidar_id = self._default_lidar_id()
            if lidar_id is None:
                return None
        return self.scene.get_lidar_at_iteration(self.iteration, lidar_id)

    def boxes(self) -> Optional[BoxDetectionsSE3]:
        """Return the 3D bounding-box detections (ground-truth labels), if any."""
        return self.scene.get_box_detections_se3_at_iteration(self.iteration)

    def ego_state(self) -> Optional[EgoStateSE3]:
        """Return the ego-vehicle state (pose, dynamics), if available."""
        return self.scene.get_ego_state_se3_at_iteration(self.iteration)

    def depth(self) -> Optional[np.ndarray]:
        """Load the precomputed sparse depth map (left image), or ``None``.

        Looks for ``<depth_root>/<log_name>/<iteration:05d>.npz`` with key
        ``depth_map``. The map is LiDAR projected into the left stereo camera:
        a ``(H, W)`` float32 array with 0 where there is no return.
        """
        if self.depth_root is None:
            return None
        path = Path(self.depth_root) / self.log_name / f"{self.iteration:05d}.npz"
        if not path.exists():
            return None
        with np.load(path) as data:
            key = "depth_map" if "depth_map" in data.files else data.files[0]
            return data[key]

    def to_stereo_sample(
        self,
        left_camera_id: CameraIdLike = DEFAULT_LEFT_CAMERA,
        right_camera_id: CameraIdLike = DEFAULT_RIGHT_CAMERA,
        lidar_id: Optional[LidarIdLike] = None,
    ) -> StereoSample:
        """Assemble the per-frame :class:`StereoSample` for preprocessing.

        :param left_camera_id: Left stereo camera id (default AV2 ``pcam_stereo_l``).
        :param right_camera_id: Right stereo camera id (default AV2 ``pcam_stereo_r``).
        :param lidar_id: Lidar to use; defaults to merged/first available.
        :raises ValueError: if the requested stereo cameras are not available.
        """
        left = self.camera(left_camera_id)
        right = self.camera(right_camera_id)
        if left is None or right is None:
            available = [c.name for c in self.available_camera_ids]
            raise ValueError(
                f"Stereo cameras {left_camera_id!r}/{right_camera_id!r} not available; "
                f"this scene exposes {available}. Pass left_camera_id/right_camera_id "
                f"for your dataset's stereo pair."
            )

        lidar = self.lidar(lidar_id)
        lidar_xyz = lidar.xyz.astype(np.float64) if lidar is not None else np.zeros((0, 3), dtype=np.float64)
        lidar_features = lidar.point_cloud_features if lidar is not None else None

        boxes = self.boxes()
        boxes_array = _boxes_to_array(boxes)
        detections = boxes.box_detections if boxes is not None else []
        boxes_labels = [str(getattr(d.attributes.default_label, "name", d.attributes.default_label)) for d in detections]
        boxes_tokens = [d.attributes.track_token for d in detections]
        boxes_velocity = (
            np.stack([np.asarray(d.velocity_3d, dtype=np.float64) for d in detections])
            if detections
            else np.zeros((0, 3), dtype=np.float64)
        )

        # 2D boxes: project the 3D boxes into the left image (auto-generated).
        boxes_2d, boxes_2d_indices = _project_boxes_2d(left, boxes_array)

        # 3D positions of returns outside every box (background geometry).
        ego = self.ego_state()
        if lidar_xyz.shape[0] and boxes_array.shape[0] and ego is not None:
            points_global = rel_to_abs_points_3d_array(ego.imu_se3, lidar_xyz)
            inside = points_3d_in_bbse3_array(points_global.astype(np.float64), boxes_array)  # (N_boxes, P)
            in_any_box = inside.any(axis=0)
        else:
            in_any_box = np.zeros((lidar_xyz.shape[0],), dtype=bool)
        points_outside = lidar_xyz[~in_any_box]

        # Calibration.
        ego_to_global = _pose_to_matrix(ego.imu_se3) if ego is not None else np.eye(4)
        left_to_ego = _pose_to_matrix(left.metadata.camera_to_imu_se3)
        right_to_ego = _pose_to_matrix(right.metadata.camera_to_imu_se3)
        baseline = float(np.linalg.norm(left_to_ego[:3, 3] - right_to_ego[:3, 3]))
        calibration = Calibration(
            left_intrinsics=_intrinsics_matrix(left.metadata.intrinsics),
            right_intrinsics=_intrinsics_matrix(right.metadata.intrinsics),
            left_to_ego=left_to_ego,
            right_to_ego=right_to_ego,
            ego_to_global=ego_to_global,
            left_to_global=_pose_to_matrix(left.camera_to_global_se3),
            right_to_global=_pose_to_matrix(right.camera_to_global_se3),
            stereo_baseline_m=baseline,
            left_is_distorted=bool(left.metadata.is_distorted),
            right_is_distorted=bool(right.metadata.is_distorted),
        )

        return StereoSample(
            dataset=self.dataset,
            log_name=self.log_name,
            scene_index=self.scene_index,
            iteration=self.iteration,
            timestamp_us=self.timestamp.time_us,
            image_left=left.image,
            image_right=right.image,
            lidar_xyz=lidar_xyz,
            lidar_features=lidar_features,
            depth_left=self.depth(),
            boxes_3d=boxes_array,
            boxes_3d_labels=boxes_labels,
            boxes_3d_track_tokens=boxes_tokens,
            boxes_3d_velocity=boxes_velocity,
            boxes_2d_left=boxes_2d,
            boxes_2d_left_box_indices=boxes_2d_indices,
            points_outside_boxes_xyz=points_outside,
            points_in_box_mask=in_any_box,
            calibration=calibration,
        )

    def _default_lidar_id(self) -> Optional[LidarID]:
        available = self.available_lidar_ids
        if not available:
            return None
        if LidarID.LIDAR_MERGED in available:
            return LidarID.LIDAR_MERGED
        return available[0]

    def __repr__(self) -> str:
        return (
            f"Frame(dataset={self.dataset!r}, log={self.log_name!r}, "
            f"scene={self.scene_index}, iter={self.iteration})"
        )


class Py123dDataset:
    """A flat, frame-indexed view over a filtered set of py123d scenes.

    Scenes are selected with a :class:`~py123d.api.SceneFilter`; every iteration
    (synchronized time step) of every matching scene becomes one indexable
    :class:`Frame`. The map-style ``__len__`` / ``__getitem__`` interface plugs
    directly into a ``torch.utils.data.DataLoader`` (call ``to_stereo_sample``
    in your ``collate``/transform) without importing torch here.

    :param data_root: Root holding converted ``logs/`` (and ``maps/``,
        ``preprocessed/``). Defaults to ``PY123D_DATA_ROOT`` or the repo
        ``data/`` dir.
    :param split_names: Split filter, e.g. ``["av2-sensor_val"]``.
    :param datasets: Dataset-name filter, e.g. ``["av2-sensor"]``.
    :param depth_root: Directory of precomputed depth maps. Defaults to
        ``<data_root>/preprocessed/depth_maps``.
    :param scene_filter: A fully-built :class:`SceneFilter`; if given, the
        individual filter kwargs above are ignored.
    :param filter_kwargs: Any other :class:`SceneFilter` argument
        (``log_names``, ``scene_uuids``, ``max_num_scenes``, ``shuffle``, ...).
    """

    def __init__(
        self,
        data_root: Optional[Union[str, Path]] = None,
        *,
        split_names: Optional[Sequence[str]] = None,
        datasets: Optional[Sequence[str]] = None,
        depth_root: Optional[Union[str, Path]] = None,
        scene_filter: Optional[SceneFilter] = None,
        **filter_kwargs,
    ) -> None:
        self.data_root = configure_dataset_paths(data_root)
        self.depth_root = Path(depth_root) if depth_root is not None else self.data_root / "preprocessed" / "depth_maps"

        if scene_filter is None:
            scene_filter = SceneFilter(
                datasets=list(datasets) if datasets is not None else None,
                split_names=list(split_names) if split_names is not None else None,
                **filter_kwargs,
            )
        self.scene_filter = scene_filter

        self.scenes: List[SceneAPI] = get_filtered_scenes(scene_filter, data_root=self.data_root)
        # Flat index: one entry per (scene, iteration) so frames are addressable
        # by a single integer. ``number_of_iterations`` counts current + future.
        self._index: List[tuple[int, int]] = [
            (scene_idx, iteration)
            for scene_idx, scene in enumerate(self.scenes)
            for iteration in range(scene.number_of_iterations)
        ]

    @property
    def scene_count(self) -> int:
        return len(self.scenes)

    def __len__(self) -> int:
        return len(self._index)

    def _make_frame(self, scene_index: int, iteration: int) -> Frame:
        return Frame(
            scene=self.scenes[scene_index],
            scene_index=scene_index,
            iteration=iteration,
            depth_root=self.depth_root,
        )

    def __getitem__(self, index: int) -> Frame:
        scene_index, iteration = self._index[index]
        return self._make_frame(scene_index, iteration)

    def __iter__(self) -> Iterator[Frame]:
        for index in range(len(self)):
            yield self[index]

    def get_frame(self, scene_index: int, iteration: int) -> Frame:
        """Return the :class:`Frame` for an explicit ``(scene_index, iteration)``."""
        return self._make_frame(scene_index, iteration)

    def frames_in_scene(self, scene_index: int) -> Iterator[Frame]:
        """Iterate the frames of a single scene in capture order."""
        for iteration in range(self.scenes[scene_index].number_of_iterations):
            yield self._make_frame(scene_index, iteration)

    def __repr__(self) -> str:
        return (
            f"Py123dDataset(data_root={str(self.data_root)!r}, "
            f"scenes={self.scene_count}, frames={len(self)})"
        )
