"""Dataset loading for the stereo-lidar-perception project.

This module is the *data* stage of the pipeline. It loads raw sensor data,
calibration and labels through the unified ``py123d`` Scene API and assembles
them into a per-frame :class:`StereoSample`, then provides the geometric
*preprocessing* representations (stereo depth/BEV, frustum, voxel, clustering)
that the network and baselines consume.

Because everything goes through :class:`py123d.api.SceneAPI`, the same code
works for any py123d dataset (KITTI-360, Argoverse 2, nuPlan, nuScenes, ...).
Switching datasets only changes the :class:`~py123d.api.SceneFilter` and the
root paths; the stereo-specific assembly assumes a left/right camera pair whose
ids are configurable (``pcam_stereo_l`` / ``pcam_stereo_r`` by default — see
:mod:`globals`). The project default is KITTI-360 (the only py123d dataset with
a real colour stereo pair; see ``docs/dataset.md``).

============================ INPUTS ============================
Read from disk (paths resolved from environment variables, see
:func:`configure_dataset_paths` and ``py123d-docs/installation.md``):

* Converted py123d logs (Arrow) under ``$PY123D_DATA_ROOT/logs`` — ego state,
  camera/lidar tables, 3D box labels, sync table.
* Original sensor blobs under the per-dataset root (e.g. KITTI-360's
  ``$KITTI360_DATA_ROOT/data_2d_raw`` + ``data_3d_raw``, AV2's
  ``$AV2_DATA_ROOT/sensor``) — the PNG/JPEG images and lidar scans (conversion
  stores only relative paths to these).
* Precomputed sparse depth maps under
  ``$PY123D_DATA_ROOT/preprocessed/depth_maps/<log>/<iteration>.npz`` (key
  ``depth_map``): LiDAR projected into the left stereo image. Optional — frames
  load ``None`` when a depth file is absent.
* A :class:`~py123d.api.SceneFilter` selecting dataset / split / scenes.

============================ OUTPUTS ===========================
One :class:`StereoSample` per frame (consumed by the representations below):

* ``image_left`` / ``image_right`` — stereo RGB pair, ``(H, W, 3)`` uint8.
* ``depth_left`` — precomputed sparse metric depth in the left image,
  ``(H, W)`` float32 (0 = no LiDAR return), or ``None`` if not available.
* ``lidar_xyz`` — full point cloud ``(P, 3)`` in the **ego** frame;
  ``lidar_features`` — dict of per-point channels (intensity, channel,
  timestamps, ...).
* ``boxes_3d`` — ground-truth 3D boxes, ``(N, 10)`` in the **global** frame
  (``BoundingBoxSE3Index``: x,y,z,qw,qx,qy,qz,length,width,height), plus
  ``boxes_3d_labels`` / ``boxes_3d_track_tokens`` / ``boxes_3d_velocity``.
* ``boxes_3d_ego`` — the same boxes in the **ego** frame (centre + orientation
  transformed, extent unchanged), aligned with ``lidar_xyz`` and the BEV grids.
  Use this — not ``boxes_3d`` — for BEV target encoding; ``boxes_3d`` stays
  global because the 2D projection below needs it there.
* ``boxes_2d_left`` — image-plane 2D boxes auto-generated by projecting the 3D
  boxes into the left camera, ``(M, 4)`` xyxy (clipped to the image), with
  ``boxes_2d_left_box_indices`` mapping each back to its row in ``boxes_3d``.
* ``points_outside_boxes_xyz`` — 3D positions (ego frame) of LiDAR returns that
  fall outside *every* 3D box (static/background geometry), plus the
  ``points_in_box_mask`` over ``lidar_xyz``.
* ``calibration`` — :class:`Calibration` with the left/right intrinsics, the
  camera->ego and ego->global extrinsics, and the stereo baseline.

Quick start::

    from data import Py123dDataset
    dataset = Py123dDataset(split_names=["kitti360_train"])
    sample = dataset[0].to_stereo_sample()   # -> StereoSample for preprocessing
"""

from __future__ import annotations

import os
from collections.abc import Callable, Iterator, Sequence
from dataclasses import dataclass, replace
from pathlib import Path

import cv2
import numpy as np
from py123d.api import SceneAPI, SceneFilter, get_filtered_scenes
from py123d.common.runtime import DatasetPaths, setup_dataset_paths
from py123d.datatypes.detections import BoxDetectionsSE3
from py123d.datatypes.sensors import Camera, CameraID, Lidar, LidarID
from py123d.datatypes.time import Timestamp
from py123d.datatypes.vehicle_state import EgoStateSE3
from py123d.geometry.geometry_index import BoundingBoxSE3Index
from py123d.geometry.transform import (abs_to_rel_se3_array,
                                       rel_to_abs_points_3d_array)
from py123d.geometry.utils.bounding_box_utils import (
    bbse3_array_to_corners_array, points_3d_in_bbse3_array)
from scipy.spatial import cKDTree

import globals as G

# Repo-local fallback root for the converted ``logs/`` + ``preprocessed/``. Prefer
# ``data/`` (the layout the KITTI-360 download script writes and the README uses),
# then ``dataset/`` (the older self-contained layout) — whichever actually holds a
# ``logs/`` dir. Picking the populated one means the notebooks / tests / scripts
# work with a bare kernel (no ``PY123D_DATA_ROOT`` exported). Env vars still win.
_REPO_ROOT = Path(__file__).resolve().parent


def _default_data_root() -> Path:
    for name in ("data", "dataset"):
        if (_REPO_ROOT / name / "logs").is_dir():
            return _REPO_ROOT / name
    return _REPO_ROOT / "dataset"


DEFAULT_DATA_ROOT = _default_data_root()

# Default stereo pair. From globals (KITTI-360 / AV2 share these enum ids).
DEFAULT_LEFT_CAMERA = G.LEFT_CAMERA
DEFAULT_RIGHT_CAMERA = G.RIGHT_CAMERA

# Per-dataset "original data root" env vars. py123d derives each dataset's
# sensor root from these (e.g. AV2_DATA_ROOT -> ``<root>/sensor``).
_DATASET_ROOT_ENV_VARS: Sequence[str] = (
    "AV2_DATA_ROOT",
    "NUPLAN_DATA_ROOT",
    "WOD_PERCEPTION_DATA_ROOT",
    "WOD_MOTION_DATA_ROOT",
    "PANDASET_DATA_ROOT",
    "KITTI360_DATA_ROOT",
    "NUSCENES_DATA_ROOT",
)

CameraIdLike = CameraID | str | int
LidarIdLike = LidarID | str | int


def configure_dataset_paths(data_root: str | Path | None = None) -> Path:
    """Point py123d at the dataset roots and return the resolved data root.

    The data root is taken from (in order): the ``data_root`` argument, the
    ``PY123D_DATA_ROOT`` environment variable, or :data:`DEFAULT_DATA_ROOT`.

    Any already-exported dataset root variable (``AV2_DATA_ROOT`` etc.) is left
    untouched; the rest default to ``data_root`` so the self-contained repo
    layout works out of the box while real installs keep their own paths.

    Must be called before any scene/sensor data is read, because the readers
    look up sensor locations through the process-global dataset paths. It is
    invoked automatically by :class:`Py123dDataset`.
    """
    env_root = os.environ.get("PY123D_DATA_ROOT")
    if env_root == "None":
        env_root = None
    resolved = Path(data_root or env_root or DEFAULT_DATA_ROOT).resolve()
    if not (resolved / "logs").exists():
        print(f"DEBUG: logs not found in {resolved}, falling back to {DEFAULT_DATA_ROOT}", flush=True)
        resolved = Path(DEFAULT_DATA_ROOT).resolve()
    print(f"DEBUG: PY123D_DATA_ROOT resolved to {resolved}", flush=True)

    os.environ["PY123D_DATA_ROOT"] = str(resolved)
    # The raw KITTI-360 sensor blobs (calibration/ data_2d_raw/ data_3d_raw) live
    # in a ``KITTI-360`` dir, NOT under the logs root — point KITTI360_DATA_ROOT
    # there when present, before the generic fill-in below defaults it to
    # ``resolved``. Check the data root first (``<root>/KITTI-360``, e.g.
    # ``dataset/KITTI-360``), then the repo top level (``<repo>/KITTI-360``).
    for kitti360_root in (resolved / "KITTI-360", _REPO_ROOT / "KITTI-360"):
        if kitti360_root.is_dir():
            os.environ.setdefault("KITTI360_DATA_ROOT", str(kitti360_root))
            break
    for env_var in _DATASET_ROOT_ENV_VARS:
        # ``setdefault`` keeps user-provided roots; only fills in the gaps.
        os.environ.setdefault(env_var, str(resolved))

    # Initialise the process-global paths from the (now-populated) environment.
    setup_dataset_paths(DatasetPaths.from_env())
    return resolved


# --------------------------------------------------------------------------- #
# Geometry helpers
# --------------------------------------------------------------------------- #
def _pose_to_matrix(pose) -> np.ndarray:
    """Convert a py123d ``PoseSE3`` to a 4x4 homogeneous transform."""
    matrix = np.eye(4, dtype=np.float64)
    matrix[:3, :3] = np.asarray(pose.rotation_matrix, dtype=np.float64)
    matrix[:3, 3] = np.asarray(pose.array, dtype=np.float64)[:3]
    return matrix


def _intrinsics_matrix(intrinsics) -> np.ndarray:
    """Build a 3x3 camera matrix from py123d ``PinholeIntrinsics`` (fx,fy,cx,cy,skew)."""
    values = np.asarray(intrinsics, dtype=np.float64).ravel()
    fx, fy, cx, cy = values[0], values[1], values[2], values[3]
    skew = values[4] if values.size > 4 else 0.0
    return np.array([[fx, skew, cx], [0.0, fy, cy], [0.0, 0.0, 1.0]],
                    dtype=np.float64)


def _boxes_to_array(boxes: BoxDetectionsSE3 | None) -> np.ndarray:
    """Stack box poses+dims into ``(N, 10)`` (``BoundingBoxSE3Index``), global frame."""
    if boxes is None or not boxes.box_detections:
        return np.zeros((0, 10), dtype=np.float64)
    return np.stack([d.bounding_box_se3.array
                     for d in boxes.box_detections]).astype(np.float64)


# Generous bound on how far a real label can sit from the ego vehicle, in
# metres. AV2/nuScenes/Waymo annotate well inside this; a *global*-frame box fed
# in by mistake lands at city-scale coordinates (often >1 km from the origin)
# and trips the guard. This is a frame-mismatch tripwire, *not* a grid crop.
SENSOR_RANGE_M = 500.0


def boxes_global_to_ego(boxes_global: np.ndarray, ego_origin) -> np.ndarray:
    """Convert ``(N, 10)`` 3D boxes from the global frame to the ego/imu frame.

    The labels in :attr:`StereoSample.boxes_3d` live in the **global** frame,
    whereas the lidar point cloud, every BEV grid and the splatted features live
    in the **ego** frame. A target encoder that rasterises box centres onto the
    BEV grid must therefore convert first, or the targets land in the wrong cells
    (a silent, non-crashing bug that simply fails to converge).

    Both the centre ``(x, y, z)`` *and* the orientation quaternion
    ``(qw, qx, qy, qz)`` are transformed (via :func:`abs_to_rel_se3_array`, the
    documented inverse of the ``rel_to_abs`` used to lift the lidar to global);
    the extent ``(length, width, height)`` is frame-invariant and copied through.

    :param boxes_global: ``(N, 10)`` array indexed by
        :class:`~py123d.geometry.BoundingBoxSE3Index`, in the global frame.
    :param ego_origin: The ego pose in the global frame — a py123d ``PoseSE3``
        (e.g. ``ego_state.imu_se3``) or its ``(7,)`` ``PoseSE3Index`` array.
    :return: ``(N, 10)`` array of the same boxes in the ego frame.
    """
    boxes_global = np.asarray(boxes_global, dtype=np.float64)
    if boxes_global.shape[0] == 0:
        return boxes_global.reshape(0, len(BoundingBoxSE3Index)).copy()

    boxes_ego = boxes_global.copy()
    # SE3 == (x, y, z, qw, qx, qy, qz); same layout as PoseSE3Index, so the pose
    # transform applies directly. EXTENT (l, w, h) is left untouched.
    boxes_ego[:, BoundingBoxSE3Index.SE3] = abs_to_rel_se3_array(
        ego_origin, boxes_global[:, BoundingBoxSE3Index.SE3])
    return boxes_ego


def assert_boxes_in_sensor_range(boxes_ego: np.ndarray,
                                 max_radius_m: float = SENSOR_RANGE_M) -> None:
    """Frame-mismatch guard: assert ego-frame box centres are sensor-scale.

    Cheap tripwire against silently feeding *global*-frame boxes where ego-frame
    boxes are expected (e.g. after a dataset swap): global centres are city-scale
    and blow past ``max_radius_m``, ego centres never do. It deliberately does
    **not** assert boxes fall inside the BEV crop — legitimate labels sit behind
    the ego or beyond the grid; cropping to ``x_range``/``y_range`` is the target
    encoder's job, not a correctness invariant of the frame conversion.

    :raises AssertionError: if any centre is non-finite or farther than
        ``max_radius_m`` from the ego origin in the x/y plane.
    """
    if boxes_ego.shape[0] == 0:
        return
    centres = boxes_ego[:, BoundingBoxSE3Index.XYZ]
    assert np.isfinite(centres).all(), "box centres contain non-finite values"
    radius = np.linalg.norm(centres[:, :2], axis=1)
    worst = float(radius.max())
    assert worst <= max_radius_m, (
        f"box centre {worst:.1f} m from ego exceeds {max_radius_m:.0f} m sensor range — "
        "boxes look like they are still in the global frame (forgot global->ego conversion?)"
    )


def _project_boxes_2d(camera: Camera, boxes_array: np.ndarray):
    """Project 3D boxes into an image and return clipped amodal 2D boxes.

    :return: ``(boxes_2d, box_indices)`` where ``boxes_2d`` is ``(M, 4)`` xyxy in
        pixels (clipped to the image) and ``box_indices`` maps each 2D box to its
        row in ``boxes_array``. Boxes with no corner in front of the camera are
        dropped.
    """
    if boxes_array.shape[0] == 0:
        return np.zeros((0, 4), dtype=np.float64), np.zeros((0, ),
                                                            dtype=np.int64)

    corners_global = bbse3_array_to_corners_array(boxes_array).reshape(
        -1, 3)  # (N*8, 3)
    pixels, in_fov, depth = camera.project_points_global(corners_global)
    pixels = pixels.reshape(-1, 8, 2)
    in_fov = in_fov.reshape(-1, 8)
    in_front = depth.reshape(-1, 8) > 0.0

    width, height = camera.metadata.width, camera.metadata.height
    boxes_2d: list[np.ndarray] = []
    indices: list[int] = []
    for i in range(boxes_array.shape[0]):
        front = in_front[i]
        if not front.any() or not in_fov[i].any():
            continue
        # Amodal extent from the corners that are in front of the camera.
        corner_px = pixels[i][front]
        x_min, y_min = corner_px.min(axis=0)
        x_max, y_max = corner_px.max(axis=0)
        boxes_2d.append(
            np.array(
                [
                    np.clip(x_min, 0, width),
                    np.clip(y_min, 0, height),
                    np.clip(x_max, 0, width),
                    np.clip(y_max, 0, height),
                ],
                dtype=np.float64,
            ))
        indices.append(i)

    if not boxes_2d:
        return np.zeros((0, 4), dtype=np.float64), np.zeros((0, ),
                                                            dtype=np.int64)
    return np.stack(boxes_2d), np.asarray(indices, dtype=np.int64)


# --------------------------------------------------------------------------- #
# Output containers
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class Calibration:
    """Camera intrinsics + extrinsics for the stereo pair (SI units, metres)."""

    left_intrinsics: np.ndarray  # (3, 3)
    right_intrinsics: np.ndarray  # (3, 3)
    left_to_ego: np.ndarray  # (4, 4) camera -> ego/imu
    right_to_ego: np.ndarray  # (4, 4)
    ego_to_global: np.ndarray  # (4, 4) ego/imu -> global
    left_to_global: np.ndarray  # (4, 4)
    right_to_global: np.ndarray  # (4, 4)
    stereo_baseline_m: float
    left_is_distorted: bool
    right_is_distorted: bool


@dataclass(frozen=True)
class StereoSample:
    """All per-frame outputs handed to the preprocessing module.

    See the module docstring for field semantics. Frames/datasets without a
    given modality leave the corresponding field empty (``None`` or a
    zero-length array), so consumers can stay dataset-agnostic.
    """

    # identity
    dataset: str
    log_name: str
    scene_index: int
    iteration: int
    timestamp_us: int

    # raw stereo + lidar (images are None when loaded with load_images=False)
    image_left: np.ndarray | None
    image_right: np.ndarray | None
    lidar_xyz: np.ndarray
    lidar_features: dict[
        str, np.ndarray] | None  # e.g. intensity, channel, timestamps

    # precomputed sparse depth (left image), may be None
    depth_left: np.ndarray | None

    # 3D labels (global frame). ``boxes_3d_ego`` is the same boxes in the ego
    # frame (centre + orientation transformed, extent unchanged), aligned with
    # ``lidar_xyz`` and the BEV grids — use it for BEV target encoding.
    boxes_3d: np.ndarray
    boxes_3d_ego: np.ndarray
    boxes_3d_labels: list[str]
    boxes_3d_track_tokens: list[str]
    boxes_3d_velocity: np.ndarray

    # 2D labels (left image, auto-generated from 3D)
    boxes_2d_left: np.ndarray
    boxes_2d_left_box_indices: np.ndarray

    # 3D positions of returns outside every box (ego frame) + membership mask
    points_outside_boxes_xyz: np.ndarray
    points_in_box_mask: np.ndarray

    # calibration (None when loaded with load_images=False)
    calibration: Calibration | None

    def __repr__(self) -> str:
        return (
            f"StereoSample(dataset={self.dataset!r}, log={self.log_name!r}, "
            f"iter={self.iteration}, boxes_3d={len(self.boxes_3d)}, "
            f"boxes_2d={len(self.boxes_2d_left)}, lidar_pts={len(self.lidar_xyz)}, "
            f"depth={'yes' if self.depth_left is not None else 'no'})")


@dataclass(frozen=True)
class Frame:
    """A single synchronized time step within a scene.

    Provides dataset-agnostic lazy accessors for individual modalities
    (:meth:`camera`, :meth:`lidar`, :meth:`boxes`, :meth:`ego_state`,
    :meth:`depth`) and the project-level :meth:`to_stereo_sample`, which bundles
    them into a :class:`StereoSample`.
    """

    scene: SceneAPI
    scene_index: int
    iteration: int
    depth_root: Path | None = None

    # -- identity / metadata -------------------------------------------------
    @property
    def dataset(self) -> str:
        return self.scene.dataset

    @property
    def split(self) -> str:
        return self.scene.split

    @property
    def location(self) -> str:
        return self.scene.location

    @property
    def log_name(self) -> str:
        return self.scene.log_name

    @property
    def scene_uuid(self) -> str:
        return self.scene.scene_uuid

    @property
    def timestamp(self) -> Timestamp:
        return self.scene.get_timestamp_at_iteration(self.iteration)

    @property
    def available_camera_ids(self) -> list[CameraID]:
        return self.scene.available_camera_ids

    @property
    def available_lidar_ids(self) -> list[LidarID]:
        return self.scene.available_lidar_ids

    # -- modality accessors --------------------------------------------------
    def camera(self, camera_id: CameraIdLike) -> Camera | None:
        """Return the :class:`Camera` (image + intrinsics/extrinsics) for ``camera_id``."""
        return self.scene.get_camera_at_iteration(self.iteration, camera_id)

    def cameras(
        self,
        camera_ids: Sequence[CameraIdLike] | None = None
    ) -> dict[CameraID, Camera]:
        """Return ``{CameraID: Camera}`` for the requested (or all available) cameras."""
        ids = list(camera_ids
                   ) if camera_ids is not None else self.available_camera_ids
        out: dict[CameraID, Camera] = {}
        for cid in ids:
            camera = self.camera(cid)
            if camera is not None:
                out[CameraID.from_arbitrary(cid)] = camera
        return out

    def lidar(self, lidar_id: LidarIdLike | None = None) -> Lidar | None:
        """Return a :class:`Lidar` point cloud.

        Defaults to the merged point cloud when present, otherwise the first
        available lidar, so callers need not know each dataset's lidar layout.
        """
        if lidar_id is None:
            lidar_id = self._default_lidar_id()
            if lidar_id is None:
                return None
        return self.scene.get_lidar_at_iteration(self.iteration, lidar_id)

    def boxes(self) -> BoxDetectionsSE3 | None:
        """Return the 3D bounding-box detections (ground-truth labels), if any."""
        return self.scene.get_box_detections_se3_at_iteration(self.iteration)

    def ego_state(self) -> EgoStateSE3 | None:
        """Return the ego-vehicle state (pose, dynamics), if available."""
        return self.scene.get_ego_state_se3_at_iteration(self.iteration)

    def depth(self) -> np.ndarray | None:
        """Load the precomputed sparse depth map (left image), or ``None``.

        Looks for ``<depth_root>/<log_name>/<iteration:05d>.npz`` with key
        ``depth_map``. The map is LiDAR projected into the left stereo camera:
        a ``(H, W)`` float32 array with 0 where there is no return.
        """
        if self.depth_root is None:
            return None
        path = Path(
            self.depth_root) / self.log_name / f"{self.iteration:05d}.npz"
        if not path.exists():
            return None
        with np.load(path) as data:
            key = "depth_map" if "depth_map" in data.files else data.files[0]
            return data[key]

    def to_stereo_sample(
        self,
        left_camera_id: CameraIdLike = DEFAULT_LEFT_CAMERA,
        right_camera_id: CameraIdLike = DEFAULT_RIGHT_CAMERA,
        lidar_id: LidarIdLike | None = None,
        load_images: bool = True,
        point_mask: bool = True,
    ) -> StereoSample:
        """Assemble the per-frame :class:`StereoSample` for preprocessing.

        The two flags exist because full assembly costs ~0.9 s/frame while the
        training loop needs almost none of it (profiled: the in-box point mask
        dominates, then image decode + 2D projection):

        * ``load_images=False`` — skip the stereo pair entirely: ``image_*``,
          ``depth_left`` and ``calibration`` are ``None``, ``boxes_2d_*`` empty.
          Enough for LiDAR training and for the camera branch fed from the
          precomputed stereo cache (which stores its own K / extrinsics).
        * ``point_mask=False`` — skip the LiDAR-in-box test (the single most
          expensive step): ``points_in_box_mask`` is all-False and
          ``points_outside_boxes_xyz`` empty, i.e. *not computed*.

        :param left_camera_id: Left stereo camera id (default ``pcam_stereo_l``;
            KITTI-360 ``image_00`` / AV2 stereo-left both map here).
        :param right_camera_id: Right stereo camera id (default ``pcam_stereo_r``;
            KITTI-360 ``image_01`` / AV2 stereo-right).
        :param lidar_id: Lidar to use; defaults to merged/first available.
        :raises ValueError: if the requested stereo cameras are not available.
        """
        left = right = None
        if load_images:
            left = self.camera(left_camera_id)
            right = self.camera(right_camera_id)
            if left is None or right is None:
                available = [c.name for c in self.available_camera_ids]
                raise ValueError(
                    f"Stereo cameras {left_camera_id!r}/{right_camera_id!r} not available; "
                    f"this scene exposes {available}. Pass left_camera_id/right_camera_id "
                    f"for your dataset's stereo pair.")

        lidar = self.lidar(lidar_id)
        lidar_xyz = lidar.xyz.astype(
            np.float64) if lidar is not None else np.zeros(
                (0, 3), dtype=np.float64)
        lidar_features = lidar.point_cloud_features if lidar is not None else None

        boxes = self.boxes()
        boxes_array = _boxes_to_array(boxes)
        detections = boxes.box_detections if boxes is not None else []
        boxes_labels = [
            str(
                getattr(d.attributes.default_label, "name",
                        d.attributes.default_label)) for d in detections
        ]
        boxes_tokens = [d.attributes.track_token for d in detections]
        boxes_velocity = (np.stack(
            [np.asarray(d.velocity_3d, dtype=np.float64)
             for d in detections]) if detections else np.zeros(
                 (0, 3), dtype=np.float64))

        # 2D boxes: project the 3D (global) boxes into the left image. The 2D
        # projection consumes global boxes, so ``boxes_array`` stays global.
        if left is not None:
            boxes_2d, boxes_2d_indices = _project_boxes_2d(left, boxes_array)
        else:
            boxes_2d = np.zeros((0, 4), dtype=np.float64)
            boxes_2d_indices = np.zeros((0, ), dtype=np.int64)

        # 3D positions of returns outside every box (background geometry).
        ego = self.ego_state()

        # Ego-frame copy of the boxes for BEV target encoding (aligned with the
        # lidar / BEV grids). Centre + orientation are transformed; extent is
        # invariant. Without an ego pose we cannot convert, so leave it empty.
        if boxes_array.shape[0] and ego is not None:
            boxes_ego = boxes_global_to_ego(boxes_array, ego.imu_se3)
            assert_boxes_in_sensor_range(boxes_ego)
        else:
            boxes_ego = np.zeros((0, 10), dtype=np.float64)
        if point_mask and lidar_xyz.shape[0] and boxes_array.shape[0] and ego is not None:
            points_global = rel_to_abs_points_3d_array(ego.imu_se3, lidar_xyz)
            inside = points_3d_in_bbse3_array(points_global.astype(np.float64),
                                              boxes_array)  # (N_boxes, P)
            in_any_box = inside.any(axis=0)
            points_outside = lidar_xyz[~in_any_box]
        else:
            in_any_box = np.zeros((lidar_xyz.shape[0], ), dtype=bool)
            # all points when the mask is trivially empty, none when skipped
            points_outside = lidar_xyz if point_mask else np.zeros(
                (0, 3), dtype=np.float64)

        # Calibration (needs the camera metadata, so only with images loaded).
        if left is not None:
            ego_to_global = _pose_to_matrix(
                ego.imu_se3) if ego is not None else np.eye(4)
            left_to_ego = _pose_to_matrix(left.metadata.camera_to_imu_se3)
            right_to_ego = _pose_to_matrix(right.metadata.camera_to_imu_se3)
            baseline = float(
                np.linalg.norm(left_to_ego[:3, 3] - right_to_ego[:3, 3]))
            calibration = Calibration(
                left_intrinsics=_intrinsics_matrix(left.metadata.intrinsics),
                right_intrinsics=_intrinsics_matrix(right.metadata.intrinsics),
                left_to_ego=left_to_ego,
                right_to_ego=right_to_ego,
                ego_to_global=ego_to_global,
                left_to_global=_pose_to_matrix(left.camera_to_global_se3),
                right_to_global=_pose_to_matrix(right.camera_to_global_se3),
                stereo_baseline_m=baseline,
                left_is_distorted=bool(left.metadata.is_distorted),
                right_is_distorted=bool(right.metadata.is_distorted),
            )
        else:
            calibration = None

        return StereoSample(
            dataset=self.dataset,
            log_name=self.log_name,
            scene_index=self.scene_index,
            iteration=self.iteration,
            timestamp_us=self.timestamp.time_us,
            image_left=left.image if left is not None else None,
            image_right=right.image if right is not None else None,
            lidar_xyz=lidar_xyz,
            lidar_features=lidar_features,
            depth_left=self.depth() if load_images else None,
            boxes_3d=boxes_array,
            boxes_3d_ego=boxes_ego,
            boxes_3d_labels=boxes_labels,
            boxes_3d_track_tokens=boxes_tokens,
            boxes_3d_velocity=boxes_velocity,
            boxes_2d_left=boxes_2d,
            boxes_2d_left_box_indices=boxes_2d_indices,
            points_outside_boxes_xyz=points_outside,
            points_in_box_mask=in_any_box,
            calibration=calibration,
        )

    def _default_lidar_id(self) -> LidarID | None:
        available = self.available_lidar_ids
        if not available:
            return None
        if LidarID.LIDAR_MERGED in available:
            return LidarID.LIDAR_MERGED
        return available[0]

    def __repr__(self) -> str:
        return (f"Frame(dataset={self.dataset!r}, log={self.log_name!r}, "
                f"scene={self.scene_index}, iter={self.iteration})")


class Py123dDataset:
    """A flat, frame-indexed view over a filtered set of py123d scenes.

    Scenes are selected with a :class:`~py123d.api.SceneFilter`; every iteration
    (synchronized time step) of every matching scene becomes one indexable
    :class:`Frame`. The map-style ``__len__`` / ``__getitem__`` interface plugs
    directly into a ``torch.utils.data.DataLoader`` (call ``to_stereo_sample``
    in your ``collate``/transform) without importing torch here.

    :param data_root: Root holding converted ``logs/`` (and ``maps/``,
        ``preprocessed/``). Defaults to ``PY123D_DATA_ROOT`` or the repo
        ``dataset/`` dir.
    :param split_names: Split filter, e.g. ``["kitti360_train"]``.
    :param datasets: Dataset-name filter, e.g. ``["kitti360"]``.
    :param depth_root: Directory of precomputed depth maps. Defaults to
        ``<data_root>/preprocessed/depth_maps``.
    :param scene_filter: A fully-built :class:`SceneFilter`; if given, the
        individual filter kwargs above are ignored.
    :param filter_kwargs: Any other :class:`SceneFilter` argument
        (``log_names``, ``scene_uuids``, ``max_num_scenes``, ``shuffle``, ...).
    """

    def __init__(
        self,
        data_root: str | Path | None = None,
        *,
        split_names: Sequence[str] | None = None,
        datasets: Sequence[str] | None = None,
        depth_root: str | Path | None = None,
        scene_filter: SceneFilter | None = None,
        **filter_kwargs,
    ) -> None:
        self.data_root = configure_dataset_paths(data_root)
        self.depth_root = Path(
            depth_root
        ) if depth_root is not None else self.data_root / "preprocessed" / "depth_maps"

        if scene_filter is None:
            scene_filter = SceneFilter(
                datasets=list(datasets) if datasets is not None else None,
                split_names=list(split_names)
                if split_names is not None else None,
                **filter_kwargs,
            )
        self.scene_filter = scene_filter

        self.scenes: List[SceneAPI] = get_filtered_scenes(scene_filter, data_root=self.data_root)
        print(f"DEBUG: found {len(self.scenes)} scenes using filter {scene_filter}", flush=True)
        # Flat index: one entry per (scene, iteration) so frames are addressable
        # by a single integer. ``number_of_iterations`` counts current + future.
        self._index: list[tuple[int, int]] = [
            (scene_idx, iteration)
            for scene_idx, scene in enumerate(self.scenes)
            for iteration in range(scene.number_of_iterations)
        ]

    @property
    def scene_count(self) -> int:
        return len(self.scenes)

    def __len__(self) -> int:
        return len(self._index)

    def _make_frame(self, scene_index: int, iteration: int) -> Frame:
        return Frame(
            scene=self.scenes[scene_index],
            scene_index=scene_index,
            iteration=iteration,
            depth_root=self.depth_root,
        )

    def __getitem__(self, index: int) -> Frame:
        scene_index, iteration = self._index[index]
        return self._make_frame(scene_index, iteration)

    def __iter__(self) -> Iterator[Frame]:
        for index in range(len(self)):
            yield self[index]

    def get_frame(self, scene_index: int, iteration: int) -> Frame:
        """Return the :class:`Frame` for an explicit ``(scene_index, iteration)``."""
        return self._make_frame(scene_index, iteration)

    def frames_in_scene(self, scene_index: int) -> Iterator[Frame]:
        """Iterate the frames of a single scene in capture order."""
        for iteration in range(self.scenes[scene_index].number_of_iterations):
            yield self._make_frame(scene_index, iteration)

    def __repr__(self) -> str:
        return (f"Py123dDataset(data_root={str(self.data_root)!r}, "
                f"scenes={self.scene_count}, frames={len(self)})")


# ===========================================================================
# ===========================================================================
#  Preprocessing — geometric input representations (stereo depth/BEV,
#  frustum, voxel, clustering). Pure geometry / classic CV; no learned weights
#  (those are the BEV branches in network.py). Operates on a StereoSample.
# ===========================================================================
# ===========================================================================


# --------------------------------------------------------------------------- #
# Geometry helpers
# --------------------------------------------------------------------------- #
def _ego_to_cam(
    xyz_ego: np.ndarray,
    cam_to_ego: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Transform ego-frame points into camera coordinates.

    :param xyz_ego:    ``(P, 3)`` points in the **ego** frame.
    :param cam_to_ego: ``(4, 4)`` camera → ego transform (from Calibration).
    :returns: ``(xyz_cam, ego_to_cam_4x4)`` — camera-frame points ``(P, 3)``
              and the 4×4 inverse transform used internally.
    """
    ego_to_cam = np.linalg.inv(cam_to_ego)
    pts_h = np.hstack(
        [xyz_ego, np.ones((len(xyz_ego), 1), dtype=xyz_ego.dtype)])
    xyz_cam = (ego_to_cam @ pts_h.T).T[:, :3]
    return xyz_cam, ego_to_cam


def _cam_to_ego(
    xyz_cam: np.ndarray,
    cam_to_ego: np.ndarray,
) -> np.ndarray:
    """Transform camera-frame points into ego coordinates.

    :param xyz_cam:    ``(P, 3)`` points in the **camera** frame.
    :param cam_to_ego: ``(4, 4)`` camera → ego transform (from Calibration).
    :returns: ego-frame points ``(P, 3)``.
    """
    pts_h = np.hstack(
        [xyz_cam, np.ones((len(xyz_cam), 1), dtype=xyz_cam.dtype)])
    xyz_ego = (cam_to_ego @ pts_h.T).T[:, :3]
    return xyz_ego


def _project_to_image(
    xyz_cam: np.ndarray,
    K: np.ndarray,
    img_w: int,
    img_h: int,
) -> tuple[np.ndarray, np.ndarray]:
    """Pinhole projection + depth & image-boundary filter.

    :param xyz_cam: ``(P, 3)`` points in camera frame.
    :param K:       ``(3, 3)`` intrinsics matrix.
    :returns: ``(uv, mask)`` — pixel coords ``(M, 2)`` (float) and boolean
              mask of length P selecting the M valid points.
    """
    in_front = xyz_cam[:, 2] > 0.0
    depth = np.where(in_front, xyz_cam[:, 2], 1.0)  # avoid div-by-zero
    uv = (K @ xyz_cam.T).T
    uv = uv[:, :2] / depth[:, None]
    valid = (in_front
             & (uv[:, 0] >= 0) & (uv[:, 0] < img_w)
             & (uv[:, 1] >= 0) & (uv[:, 1] < img_h))
    return uv, valid


# ===========================================================================
# 1.  Stereo depth → geometric BEV  (classic CV, no learning)
# ===========================================================================
@dataclass
class StereoSGBMConfig:
    """All knobs for the SGBM matcher and the disparity→depth conversion.

    The SGBM smoothness penalties follow the OpenCV convention
    ``P = factor · channels · block_size²`` so ``block_size`` can be tuned
    without re-tuning ``P1`` / ``P2`` by hand.
    """

    # ---- disparity search (FULL-res pixels; multiple of 16) ----
    min_disparity: int = 0
    num_disparities: int = 256
    block_size: int = 5  # odd, typically 3..11
    # ---- smoothness (P1 < P2) ----
    p1_factor: int = 8
    p2_factor: int = 32
    # ---- post-match consistency / cleanup ----
    uniqueness_ratio: int = 10
    speckle_window_size: int = 100
    speckle_range: int = 2
    disp12_max_diff: int = 1
    pre_filter_cap: int = 63
    mode: int = cv2.STEREO_SGBM_MODE_SGBM_3WAY

    # ---- matcher selection ----
    #: ``"sgbm"`` = raw SGBM (default, back-compat). ``"sgbm_wls"`` = SGBM plus a
    #: WLS post-filter — left/right consistency confidence + edge-aware
    #: smoothing/hole-filling. Uses ``cv2.ximgproc.DisparityWLSFilter`` (the
    #: canonical filter) when the ``opencv-contrib`` module is present; otherwise
    #: a dependency-free built-in equivalent runs (LR check + guided filter), so
    #: the option always works. Everything downstream keys off the disparity, so
    #: this is the only knob that changes.
    matcher: str = "sgbm"
    # ---- WLS post-filter (only used when matcher == "sgbm_wls") ----
    wls_lambda: float = 8000.0  # smoothness weight (ximgproc ``lambda``)
    wls_sigma: float = 1.5  # edge sensitivity (ximgproc ``sigmaColor``)
    wls_lr_max_diff: float = 1.0  # left-right consistency threshold (px)
    wls_radius: int = 8  # guided-filter radius (built-in fallback only)
    wls_eps: float = 1e-3  # guided-filter regularisation (built-in fallback only)
    wls_min_valid_frac: float = 0.05  # drop cells with too few valid neighbours (fallback)

    # ---- depth conversion / filtering ----
    min_depth_m: float = 0.5
    max_depth_m: float = 80.0

    # ---- speed: matching is done at ``downscale`` of full resolution ----
    #: Rectification is always full-res; only the matching is run on the
    #: downscaled rectified pair, then the disparity is scaled back to full
    #: res, so metric depth is unaffected. ``num_disparities`` is the *full-res*
    #: search range; it is scaled internally for the downscaled matcher.
    #: 1.0 = full res. KITTI-360's rectified pair is already small
    #: (~1408×376), so full-res matching is cheap and gives the best disparity.
    #: Drop to 0.5 for large sensors (e.g. AV2's 2048×1550, ~4× faster).
    downscale: float = 1.0


@dataclass
class StereoGeomBEVConfig:
    """BEV grid for the *geometric* :func:`stereo_bev` — defaults = shared grid.

    Named ``StereoGeomBEVConfig`` to distinguish it from the *learned*
    ``network.StereoBEVConfig`` (the splat-branch config). This one drives the
    classic, non-learned stereo BEV only.
    """

    x_range: tuple[float, float] = G.X_RANGE  # forward
    y_range: tuple[float, float] = G.Y_RANGE  # lateral
    z_range: tuple[float, float] = G.Z_RANGE  # height pre-filter
    bev_res_m: float = G.BEV_RES_M
    append_rgb: bool = True  # add mean RGB channels


@dataclass
class Rectification:
    """Output of :func:`build_rectification` — everything SGBM + lift need.

    All quantities are at **full image resolution**. Down-scaling for speed is
    applied only to the matching step (see :func:`stereo_depth`), never here, so
    ``Q`` / ``fx_rect`` always describe the full-res rectified geometry.
    """

    map_lx: np.ndarray  # left  remap x (for cv2.remap)
    map_ly: np.ndarray  # left  remap y
    map_rx: np.ndarray  # right remap x
    map_ry: np.ndarray  # right remap y
    Q: np.ndarray  # (4, 4) disparity→3D reprojection matrix
    R1: np.ndarray  # (3, 3) rotates original-left cam → rectified-left cam
    P1: np.ndarray  # (3, 4) rectified-left projection matrix
    size: tuple[int, int]  # (W, H) of the rectified image
    fx_rect: float  # rectified focal length (pixels)
    baseline_m: float  # stereo baseline (metres)


def build_rectification(
    calib: Calibration,
    image_hw: tuple[int, int],
) -> Rectification:
    """Build the full-res stereo rectification maps + reprojection matrix ``Q``.

    :param calib:    Sample :class:`~data.Calibration` (intrinsics + extrinsics).
    :param image_hw: Original ``(H, W)`` of the stereo images.
    """
    h, w = image_hw
    KL = calib.left_intrinsics.astype(np.float64)
    KR = calib.right_intrinsics.astype(np.float64)
    dist = np.zeros(5)  # stereo pair is undistorted (verified in docs/data.md)

    # Relative pose left→right:  X_right = R · X_left + T   (OpenCV convention).
    T_l2r = np.linalg.inv(calib.right_to_ego) @ calib.left_to_ego
    R = T_l2r[:3, :3]
    T = T_l2r[:3, 3]

    R1, R2, P1, P2, Q, _roi1, _roi2 = cv2.stereoRectify(
        KL,
        dist,
        KR,
        dist,
        (w, h),
        R,
        T,
        flags=cv2.CALIB_ZERO_DISPARITY,
        alpha=0,
    )

    map_lx, map_ly = cv2.initUndistortRectifyMap(KL, dist, R1, P1, (w, h),
                                                 cv2.CV_32FC1)
    map_rx, map_ry = cv2.initUndistortRectifyMap(KR, dist, R2, P2, (w, h),
                                                 cv2.CV_32FC1)

    return Rectification(
        map_lx=map_lx,
        map_ly=map_ly,
        map_rx=map_rx,
        map_ry=map_ry,
        Q=Q,
        R1=R1,
        P1=P1,
        size=(w, h),
        fx_rect=float(P1[0, 0]),
        baseline_m=float(calib.stereo_baseline_m),
    )


def _build_matcher(cfg: StereoSGBMConfig) -> "cv2.StereoSGBM":
    ch = 1  # matching on grayscale
    return cv2.StereoSGBM_create(
        minDisparity=cfg.min_disparity,
        numDisparities=cfg.num_disparities,
        blockSize=cfg.block_size,
        P1=cfg.p1_factor * ch * cfg.block_size**2,
        P2=cfg.p2_factor * ch * cfg.block_size**2,
        disp12MaxDiff=cfg.disp12_max_diff,
        uniquenessRatio=cfg.uniqueness_ratio,
        speckleWindowSize=cfg.speckle_window_size,
        speckleRange=cfg.speckle_range,
        preFilterCap=cfg.pre_filter_cap,
        mode=cfg.mode,
    )


def compute_disparity(
    rect_left: np.ndarray,
    rect_right: np.ndarray,
    cfg: StereoSGBMConfig | None = None,
) -> np.ndarray:
    """Run SGBM on an **already rectified** stereo pair.

    :param rect_left:  rectified left image  ``(H, W, 3)`` uint8 or ``(H, W)``.
    :param rect_right: rectified right image, same shape.
    :returns: float32 disparity ``(H, W)`` in pixels; ``<= 0`` marks invalid
        (occluded / unmatched) pixels.
    """
    cfg = cfg or StereoSGBMConfig()
    if rect_left.ndim == 3:
        gl = cv2.cvtColor(rect_left, cv2.COLOR_RGB2GRAY)
        gr = cv2.cvtColor(rect_right, cv2.COLOR_RGB2GRAY)
    else:
        gl, gr = rect_left, rect_right

    matcher = _build_matcher(cfg)
    disp = matcher.compute(gl, gr).astype(
        np.float32) / 16.0  # SGBM fixed-point
    disp[disp < cfg.min_disparity + 1e-3] = 0.0
    return disp


def _guided_filter_hole_aware(
    guide: np.ndarray,
    src: np.ndarray,
    mask: np.ndarray,
    radius: int,
    eps: float,
) -> tuple[np.ndarray, np.ndarray]:
    """Edge-aware guided filter (He et al., 2010) that ignores invalid pixels.

    The guided filter smooths ``src`` while snapping its transitions to edges in
    ``guide``. Here the box statistics are normalised by the local count of
    *valid* pixels, so invalid (hole) pixels neither pollute the statistics nor
    stay empty: they are filled from valid neighbours, edge-awarely.

    :param guide: grayscale left image in ``[0, 1]`` (the edge reference).
    :param src:   disparity map, ``0`` at invalid pixels.
    :param mask:  ``0/1`` validity map, same shape as ``src``.
    :param radius: box-filter radius (window = ``2·radius+1``).
    :param eps:   regularisation (larger → smoother, softer edges).
    :returns: ``(filtered, density)`` — the filtered disparity and the local
        valid fraction (``box(mask)``) used to reject barely-supported cells.
    """
    k = (2 * radius + 1, 2 * radius + 1)

    def box(im: np.ndarray) -> np.ndarray:
        return cv2.boxFilter(im.astype(np.float32), -1, k, normalize=True)

    density = box(mask)
    n = density + 1e-6  # local valid fraction (avoid div-by-zero)
    mean_I = box(guide * mask) / n
    mean_p = box(src * mask) / n
    mean_Ip = box(guide * src * mask) / n
    mean_II = box(guide * guide * mask) / n
    cov_Ip = mean_Ip - mean_I * mean_p
    var_I = mean_II - mean_I * mean_I
    a = cov_Ip / (var_I + eps)
    b = mean_p - a * mean_I
    filtered = box(a * mask) / n * guide + box(b * mask) / n
    return filtered.astype(np.float32), density


def compute_disparity_wls(
    rect_left: np.ndarray,
    rect_right: np.ndarray,
    cfg: StereoSGBMConfig | None = None,
) -> np.ndarray:
    """SGBM disparity with a **WLS post-filter** (``matcher='sgbm_wls'``).

    A weighted-least-squares style clean-up of the raw SGBM disparity, targeting
    exactly the failure mode of block matching: the occluded-edge / textureless
    outliers that dominate the far-range RMSE (see ``docs/perception_pipeline.md``
    §4.5). Two effects:

    * **left/right consistency** — a match is trusted only if the left disparity
      and the (independently matched) right disparity agree at the corresponding
      pixel; inconsistent pixels (occlusions, mismatches) are dropped.
    * **edge-aware smoothing + hole-filling** — the trusted disparity is smoothed
      and its gaps filled while snapping transitions to image edges.

    Prefers ``cv2.ximgproc.DisparityWLSFilter`` (the canonical filter, from
    ``opencv-contrib``). When ``ximgproc`` is not installed a dependency-free
    equivalent runs instead — left/right consistency via the horizontal-flip
    trick + :func:`_guided_filter_hole_aware` — so the option works out of the
    box and upgrades automatically to the canonical filter if contrib is added.

    :returns: float32 disparity ``(H, W)`` in pixels; ``<= 0`` marks invalid.
    """
    cfg = cfg or StereoSGBMConfig()
    if rect_left.ndim == 3:
        gl = cv2.cvtColor(rect_left, cv2.COLOR_RGB2GRAY)
        gr = cv2.cvtColor(rect_right, cv2.COLOR_RGB2GRAY)
    else:
        gl, gr = rect_left, rect_right

    left = _build_matcher(cfg)

    # ---- canonical path: opencv-contrib DisparityWLSFilter ----
    ximgproc = getattr(cv2, "ximgproc", None)
    if ximgproc is not None:
        right = ximgproc.createRightMatcher(left)
        disp_l = left.compute(gl, gr)  # int16 fixed-point (×16)
        disp_r = right.compute(gr, gl)
        wls = ximgproc.createDisparityWLSFilter(left)
        wls.setLambda(cfg.wls_lambda)
        wls.setSigmaColor(cfg.wls_sigma)
        filtered = wls.filter(disp_l, gl, disparity_map_right=disp_r)
        disp = filtered.astype(np.float32) / 16.0
        disp[disp < cfg.min_disparity + 1e-3] = 0.0
        return disp

    # ---- fallback: LR consistency + hole-aware guided filter (no contrib) ----
    disp_l = left.compute(gl, gr).astype(np.float32) / 16.0
    # right-image disparity via the horizontal-flip trick (no createRightMatcher):
    # SGBM on the mirrored, swapped pair, flipped back, is the right-view disparity.
    disp_r = left.compute(np.ascontiguousarray(gr[:, ::-1]),
                          np.ascontiguousarray(gl[:, ::-1])).astype(np.float32) / 16.0
    disp_r = disp_r[:, ::-1]

    h, w = disp_l.shape
    xs = np.broadcast_to(np.arange(w), (h, w))
    rows = np.broadcast_to(np.arange(h)[:, None], (h, w))
    xr = np.round(xs - disp_l).astype(np.int64)  # right pixel each left pixel maps to
    disp_r_at = disp_r[rows, np.clip(xr, 0, w - 1)]
    consistent = ((disp_l > cfg.min_disparity) & (xr >= 0) &
                  (np.abs(disp_l - disp_r_at) <= cfg.wls_lr_max_diff))
    disp_lr = np.where(consistent, disp_l, 0.0).astype(np.float32)

    guide = gl.astype(np.float32) / 255.0
    mask = (disp_lr > 0).astype(np.float32)
    filtered, density = _guided_filter_hole_aware(guide, disp_lr, mask,
                                                  cfg.wls_radius, cfg.wls_eps)
    disp = np.where(density > cfg.wls_min_valid_frac, filtered, 0.0).astype(np.float32)
    disp[disp < cfg.min_disparity + 1e-3] = 0.0
    return disp


#: Registry for **learned** stereo matchers (RAFT-Stereo, IGEV-Stereo, ...).
#: Register a callable ``(rect_left, rect_right, cfg) -> disparity (H, W) float32``
#: (full-res pixels, ``<= 0`` = invalid) under a name, then set
#: ``StereoSGBMConfig.matcher`` to that name. The heavy model code + weights stay
#: an *optional external* dependency (imported by the registrant, like
#: ``ultralytics`` for the YOLO backbone) so the core preprocessing never depends
#: on them. Example::
#:
#:     import data
#:     data.LEARNED_MATCHERS["igev"] = my_igev_disparity   # your adapter
#:     sd = data.stereo_depth(sample, StereoSGBMConfig(matcher="igev"))
LEARNED_MATCHERS: dict[str, "Callable[..., np.ndarray]"] = {}


def _match_disparity(
    rect_left: np.ndarray,
    rect_right: np.ndarray,
    cfg: StereoSGBMConfig,
) -> np.ndarray:
    """Run the stereo matcher selected by ``cfg.matcher`` on a rectified pair.

    Built-in matchers are ``"sgbm"`` and ``"sgbm_wls"``; any name present in
    :data:`LEARNED_MATCHERS` dispatches to the registered learned matcher.
    """
    if cfg.matcher == "sgbm":
        return compute_disparity(rect_left, rect_right, cfg)
    if cfg.matcher == "sgbm_wls":
        return compute_disparity_wls(rect_left, rect_right, cfg)
    learned = LEARNED_MATCHERS.get(cfg.matcher)
    if learned is not None:
        return learned(rect_left, rect_right, cfg)
    raise ValueError(
        f"unknown matcher {cfg.matcher!r}; expected 'sgbm', 'sgbm_wls', or a "
        f"name registered in data.LEARNED_MATCHERS ({list(LEARNED_MATCHERS)})")


def disparity_to_depth(disp: np.ndarray, fx: float,
                       baseline_m: float) -> np.ndarray:
    """Convert disparity (pixels) to metric depth ``z = fx · baseline / disp``.

    Invalid (``disp <= 0``) pixels map to ``0.0``.
    """
    depth = np.zeros_like(disp, dtype=np.float32)
    valid = disp > 0
    depth[valid] = (fx * baseline_m) / disp[valid]
    return depth


@dataclass
class StereoDepth:
    """Bundle returned by :func:`stereo_depth`."""

    depth: np.ndarray  # (H', W') metric depth, rectified-left frame, 0=invalid
    disparity: np.ndarray  # (H', W') disparity, pixels
    rect_left: np.ndarray  # (H', W', 3) rectified left image (for colour / debug)
    rect: Rectification  # rectification used (carries Q, R1, sizes)
    depth_left: np.ndarray  # (H, W) depth re-projected into the ORIGINAL left image


def stereo_depth(
    sample: StereoSample,
    cfg: StereoSGBMConfig | None = None,
) -> StereoDepth:
    """Compute stereo depth for a :class:`~data.StereoSample`.

    Pipeline: rectify → SGBM disparity → metric depth. The headline
    ``depth`` is in the **rectified left** frame (where SGBM works); a
    convenience ``depth_left`` re-projects it back into the **original left
    image** so it lines up with ``sample.depth_left`` (the sparse LiDAR depth)
    for evaluation / fusion.
    """
    cfg = cfg or StereoSGBMConfig()
    h, w = sample.image_left.shape[:2]
    rect = build_rectification(sample.calibration, (h, w))

    # ---- remap both views into the (full-res) rectified frame ----
    rect_left = cv2.remap(sample.image_left, rect.map_lx, rect.map_ly,
                          cv2.INTER_LINEAR)
    rect_right = cv2.remap(sample.image_right, rect.map_rx, rect.map_ry,
                           cv2.INTER_LINEAR)

    # ---- disparity (matched on the downscaled pair, scaled back to full res) ----
    s = cfg.downscale
    if s < 1.0:
        lo = cv2.resize(rect_left,
                        None,
                        fx=s,
                        fy=s,
                        interpolation=cv2.INTER_AREA)
        ro = cv2.resize(rect_right,
                        None,
                        fx=s,
                        fy=s,
                        interpolation=cv2.INTER_AREA)
        nd = max(16, int(round(cfg.num_disparities * s / 16)) * 16)
        mcfg = replace(cfg, num_disparities=nd)
        disp_s = _match_disparity(lo, ro, mcfg)
        disp = cv2.resize(disp_s, (w, h), interpolation=cv2.INTER_NEAREST) / s
    else:
        disp = _match_disparity(rect_left, rect_right, cfg)

    # ---- disparity → depth (rectified-left frame) ----
    depth = disparity_to_depth(disp, rect.fx_rect, rect.baseline_m)
    depth[(depth < cfg.min_depth_m) | (depth > cfg.max_depth_m)] = 0.0

    # ---- re-project the dense depth into the ORIGINAL left image ----
    depth_left = _depth_to_original_left(depth, rect, sample.calibration,
                                         (h, w), cfg)

    return StereoDepth(
        depth=depth,
        disparity=disp,
        rect_left=rect_left,
        rect=rect,
        depth_left=depth_left,
    )


def _depth_to_original_left(
    depth_rect: np.ndarray,
    rect: Rectification,
    calib: Calibration,
    orig_hw: tuple[int, int],
    cfg: StereoSGBMConfig,
) -> np.ndarray:
    """Re-project rectified-frame depth into the original (full-res) left image.

    Builds a ``(H, W)`` depth map in the original left image, keeping the
    nearest surface per pixel (z-buffer), so it is directly comparable to
    ``sample.depth_left`` (sparse LiDAR depth in the same frame).
    """
    h, w = orig_hw
    xyz_rect, valid = _reproject_to_3d(depth_rect, rect, cfg)
    if xyz_rect.shape[0] == 0:
        return np.zeros((h, w), dtype=np.float32)

    # rectified-left → original-left camera frame
    xyz_left = (rect.R1.T @ xyz_rect.T).T  # (P, 3)
    z = xyz_left[:, 2]
    front = z > cfg.min_depth_m
    xyz_left, z = xyz_left[front], z[front]

    KL = calib.left_intrinsics.astype(np.float64)
    uv = (KL @ xyz_left.T).T
    u = np.round(uv[:, 0] / z).astype(np.int64)
    v = np.round(uv[:, 1] / z).astype(np.int64)
    inb = (u >= 0) & (u < w) & (v >= 0) & (v < h)
    u, v, z = u[inb], v[inb], z[inb]

    out = np.full((h, w), np.inf, dtype=np.float32)
    # nearest-surface z-buffer via sorted scatter (closest written last)
    order = np.argsort(-z)
    out[v[order], u[order]] = z[order]
    out[~np.isfinite(out)] = 0.0
    return out


def _reproject_to_3d(
    depth_rect: np.ndarray,
    rect: Rectification,
    cfg: StereoSGBMConfig,
) -> tuple[np.ndarray, np.ndarray]:
    """Reproject a rectified depth map to 3-D points in the rectified-left frame.

    :returns: ``(xyz (P, 3), valid_mask (H'*W',))`` where ``xyz`` are the points
        with finite, in-range depth.
    """
    disp = np.zeros_like(depth_rect)
    m = depth_rect > 0
    # invert depth back to disparity for cv2.reprojectImageTo3D (uses Q)
    disp[m] = (rect.fx_rect * rect.baseline_m) / depth_rect[m]
    xyz = cv2.reprojectImageTo3D(disp.astype(np.float32),
                                 rect.Q.astype(np.float32))
    xyz = xyz.reshape(-1, 3)
    valid = m.reshape(-1) & np.isfinite(xyz).all(axis=1)
    return xyz[valid], valid


def stereo_point_cloud(
    sample: StereoSample,
    cfg: StereoSGBMConfig | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Lift the stereo depth into an **ego-frame** coloured point cloud.

    The returned cloud is in the same frame as ``sample.lidar_xyz``, so it can
    be dropped straight into any of the LiDAR consumers (BEV, voxels, frustum).

    :returns: ``(xyz_ego (P, 3) float32, rgb (P, 3) uint8)``.
    """
    cfg = cfg or StereoSGBMConfig()
    sd = stereo_depth(sample, cfg)

    xyz_rect, valid = _reproject_to_3d(sd.depth, sd.rect, cfg)
    if xyz_rect.shape[0] == 0:
        return np.zeros((0, 3), np.float32), np.zeros((0, 3), np.uint8)

    # rectified-left → original-left → ego
    xyz_left = (sd.rect.R1.T @ xyz_rect.T).T
    cam2ego = sample.calibration.left_to_ego.astype(np.float64)
    xyz_ego = (cam2ego[:3, :3] @ xyz_left.T).T + cam2ego[:3, 3]

    rgb = sd.rect_left.reshape(-1, 3)[valid]
    return xyz_ego.astype(np.float32), rgb.astype(np.uint8)


def stereo_bev(
    sample: StereoSample,
    cfg: StereoSGBMConfig | None = None,
    bev_cfg: StereoGeomBEVConfig | None = None,
) -> np.ndarray:
    """Build a geometric Bird's-Eye-View from the stereo point cloud.

    The grid is pixel-aligned with the LiDAR (PointPillars) and camera
    (MonoBEV) BEVs — same ``x_range`` / ``y_range`` / resolution — so the three
    maps can be concatenated channel-wise for fusion.

    Channels (``C``)::

        0  occupancy (binary)
        1  log-density
        2  max  height (normalised over z_range)
        3  mean height (normalised over z_range)
        4  mean R   ┐ only when bev_cfg.append_rgb
        5  mean G   │
        6  mean B   ┘

    :returns: ``(C, nx, ny)`` float32 BEV, ``ix`` along x (forward), ``iy``
        along y (lateral) — matching :class:`network.PointPillarsScatter`.
    """
    bcfg = bev_cfg or StereoGeomBEVConfig()
    xyz, rgb = stereo_point_cloud(sample, cfg)

    nx = int(round((bcfg.x_range[1] - bcfg.x_range[0]) / bcfg.bev_res_m))
    ny = int(round((bcfg.y_range[1] - bcfg.y_range[0]) / bcfg.bev_res_m))
    C = 7 if bcfg.append_rgb else 4
    bev = np.zeros((C, nx, ny), dtype=np.float32)
    if xyz.shape[0] == 0:
        return bev

    x, y, z = xyz[:, 0], xyz[:, 1], xyz[:, 2]
    m = ((x >= bcfg.x_range[0]) & (x < bcfg.x_range[1]) &
         (y >= bcfg.y_range[0]) & (y < bcfg.y_range[1]) &
         (z >= bcfg.z_range[0]) & (z < bcfg.z_range[1]))
    x, y, z = x[m], y[m], z[m]
    if x.shape[0] == 0:
        return bev

    ix = ((x - bcfg.x_range[0]) / bcfg.bev_res_m).astype(np.int64).clip(
        0, nx - 1)
    iy = ((y - bcfg.y_range[0]) / bcfg.bev_res_m).astype(np.int64).clip(
        0, ny - 1)

    z_norm = ((z - bcfg.z_range[0]) /
              (bcfg.z_range[1] - bcfg.z_range[0])).clip(0.0, 1.0)

    count = np.zeros((nx, ny), dtype=np.float32)
    np.add.at(count, (ix, iy), 1.0)
    occ = count > 0

    bev[0, occ] = 1.0  # occupancy
    bev[1] = np.log1p(count) / np.log1p(count.max())  # log density

    np.maximum.at(bev[2], (ix, iy), z_norm)  # max height
    np.add.at(bev[3], (ix, iy), z_norm)  # mean height (sum→/count)
    bev[3, occ] /= count[occ]

    if bcfg.append_rgb:
        rgb_m = rgb[m].astype(np.float32) / 255.0
        for k in range(3):
            np.add.at(bev[4 + k], (ix, iy), rgb_m[:, k])
            bev[4 + k][occ] /= count[occ]

    return bev


# --------------------------------------------------------------------------- #
# Stereo input cache — precomputed camera-branch inputs
#
# SGBM depth is CPU-expensive (~1-2 s/frame) and depends only on the images,
# never on network weights, so training pays for it *once*: precompute the
# camera-branch inputs (rectified-left image + depth, already resized to the
# backbone resolution, plus the matching K and camera→ego transform) and load
# them per step. <1 MB/frame vs ~50 MB for the full rectification bundle.
# --------------------------------------------------------------------------- #
def stereo_cache_root(data_root: str | Path | None = None,
                      matcher: str = "sgbm") -> Path:
    """Default cache dir for a matcher's precomputed camera-branch inputs.

    ``sgbm`` keeps the historical ``<data_root>/preprocessed/stereo_inputs`` path;
    any other matcher gets its own ``stereo_inputs_<matcher>`` sibling so caches
    from different depth sources (e.g. ``sgbm`` vs ``igev``) never collide — both
    can coexist on disk for the StereoBEV depth-source ablation.
    """
    root = Path(data_root or os.environ.get("PY123D_DATA_ROOT") or DEFAULT_DATA_ROOT)
    sub = "stereo_inputs" if matcher == "sgbm" else f"stereo_inputs_{matcher}"
    return root / "preprocessed" / sub


def stereo_cache_path(cache_root: str | Path, log_name: str, iteration: int) -> Path:
    return Path(cache_root) / log_name / f"{iteration:05d}.npz"


def stereo_branch_inputs(
    sample: StereoSample,
    target_hw: tuple[int, int] = (192, 640),
    sgbm_cfg: StereoSGBMConfig | None = None,
    sd: StereoDepth | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Everything the camera branch consumes, at backbone input resolution.

    This is the single recipe shared by the live path
    (:meth:`network.StereoBEVBranch.forward`) and the precomputed cache, so
    cached and uncached training see byte-identical inputs.

    :param sd: Precomputed :class:`StereoDepth`; computed here when ``None``.
    :returns: ``(image, depth, K, T_cam2ego)`` — rectified-left RGB ``(h, w, 3)``
        uint8, metric depth ``(h, w)`` float32 (0 = invalid), intrinsics ``(3, 3)``
        scaled to ``target_hw``, and rectified-left → ego ``(4, 4)``, all float32.
    """
    if sd is None:
        sd = stereo_depth(sample, sgbm_cfg)
    th, tw = target_hw
    ih, iw = sd.rect_left.shape[:2]

    image = cv2.resize(sd.rect_left, (tw, th), interpolation=cv2.INTER_AREA)
    depth = cv2.resize(sd.depth, (tw, th), interpolation=cv2.INTER_NEAREST)

    K = sd.rect.P1[:3, :3].astype(np.float32).copy()
    K[0] *= tw / iw  # fx, cx
    K[1] *= th / ih  # fy, cy

    R1T = np.eye(4)
    R1T[:3, :3] = sd.rect.R1.T
    T_cam2ego = (sample.calibration.left_to_ego @ R1T).astype(np.float32)
    return image, depth.astype(np.float32), K, T_cam2ego


def load_stereo_inputs(cache_root: str | Path, log_name: str, iteration: int):
    """Load one cached ``(image, depth, K, T_cam2ego)`` bundle, or ``None``."""
    path = stereo_cache_path(cache_root, log_name, iteration)
    if not path.exists():
        return None
    with np.load(path) as z:
        return z["image"], z["depth"], z["K"], z["T_cam2ego"]


def precompute_stereo_inputs(
    frames,
    cache_root: str | Path | None = None,
    target_hw: tuple[int, int] = (192, 640),
    sgbm_cfg: StereoSGBMConfig | None = None,
    overwrite: bool = False,
    log_every: int = 25,
) -> Path:
    """Precompute the camera-branch input bundle for every frame.

    The depth source is whatever ``sgbm_cfg.matcher`` selects — ``"sgbm"``
    (default), ``"sgbm_wls"``, or any learned matcher registered in
    :data:`LEARNED_MATCHERS` (e.g. ``"igev"``; register it first, see
    ``igev_matcher.register``). A learned matcher is GPU-expensive but, like
    SGBM, depends only on the images, so the cache pays it **once** and training
    reads dense depth per step at zero marginal cost.

    :param frames: Iterable of :class:`Frame` (e.g. a :class:`Py123dDataset`).
    :param cache_root: Output dir; when ``None``, defaults to
        :func:`stereo_cache_root` **for the config's matcher**, so an ``igev``
        run lands in ``stereo_inputs_igev`` and never clobbers the ``sgbm`` cache.
    :param sgbm_cfg: Matcher + depth config; its ``matcher`` field picks the
        depth source (kept named ``sgbm_cfg`` for back-compat).
    :returns: The cache root written to. Existing files are skipped unless
        ``overwrite`` — safe to re-run / resume.
    """
    if cache_root is None:
        matcher = sgbm_cfg.matcher if sgbm_cfg is not None else "sgbm"
        cache_root = stereo_cache_root(matcher=matcher)
    else:
        cache_root = Path(cache_root)
    n_done = n_skipped = 0
    for i, frame in enumerate(frames):
        path = stereo_cache_path(cache_root, frame.log_name, frame.iteration)
        if path.exists() and not overwrite:
            n_skipped += 1
            continue
        # The cache only stores image + depth + K + extrinsic, so skip the
        # in-box point mask / box assembly (the dominant ~0.9 s/frame cost).
        try:
            sample = frame.to_stereo_sample(point_mask=False)
            image, depth, K, T = stereo_branch_inputs(sample, target_hw, sgbm_cfg)
        except Exception as e:  # noqa: BLE001 — re-raised with context below
            # A corrupt/truncated raw PNG surfaces here as an opaque OpenCV
            # ``cvtColor !_src.empty()`` assertion from deep inside py123d's
            # image reader, with no hint at *which* frame. Name it so the fix
            # (re-extract, or copy a neighbour over the bad file) is obvious.
            raise RuntimeError(
                f"failed to build stereo inputs for {frame.log_name}"
                f"#{frame.iteration} — likely a corrupt/truncated raw image "
                f"(check image_00/image_01 data_rect PNGs for this drive). "
                f"Original error: {type(e).__name__}: {e}") from e
        path.parent.mkdir(parents=True, exist_ok=True)
        np.savez_compressed(path, image=image, depth=depth, K=K, T_cam2ego=T)
        n_done += 1
        if log_every and (n_done % log_every == 0):
            print(f"  precomputed {n_done} frames (+{n_skipped} cached) ...")
    print(f"stereo input cache: {n_done} written, {n_skipped} already cached "
          f"→ {cache_root}")
    return cache_root


# ===========================================================================
# 2.  Frustum
# ===========================================================================
@dataclass
class FrustumConfig:
    """Configuration for :func:`frustum_points`."""
    append_rgb: bool = True  # append left-image RGB to XYZ
    depth_normalise: bool = True  # normalise Z by frustum depth range
    min_depth_m: float = 0.5  # discard closer returns
    max_depth_m: float = 70.0  # discard farther returns
    frustum_frame: bool = True  # rotate so centroid is at +Z axis


def frustum_points(
    sample: StereoSample,
    box_index: int = 0,
    config: FrustumConfig | None = None,
) -> np.ndarray:
    """Extract a camera-frustum point cloud for one 2-D detection box.

    Selects LiDAR returns whose left-image projection falls inside
    ``sample.boxes_2d_left[box_index]`` (xyxy) and packages them into a
    local frustum frame.  RGB is optionally appended from the left image.

    :param sample:    A :class:`~data.StereoSample`.
    :param box_index: Which row of ``sample.boxes_2d_left`` to use.
    :param config:    :class:`FrustumConfig`; uses defaults when ``None``.
    :returns: Float32 array ``(P, D)`` where D is 3 (XYZ) or 6 (XYZ+RGB).
              Returns an empty ``(0, D)`` array when no points fall inside.
    :raises IndexError: if ``box_index`` is out of range.
    """
    cfg = config or FrustumConfig()
    calib = sample.calibration
    D = 6 if cfg.append_rgb else 3

    if sample.boxes_2d_left.shape[
            0] == 0 or box_index >= sample.boxes_2d_left.shape[0]:
        raise IndexError(
            f"box_index={box_index} but sample has {sample.boxes_2d_left.shape[0]} 2D boxes."
        )

    box_xyxy = sample.boxes_2d_left[box_index]  # (4,) x1,y1,x2,y2
    x1, y1, x2, y2 = box_xyxy
    img_h, img_w = sample.image_left.shape[:2]

    xyz_ego = sample.lidar_xyz.astype(np.float32)
    if xyz_ego.shape[0] == 0:
        return np.zeros((0, D), dtype=np.float32)

    # --- ego → camera ---
    xyz_cam, _ = _ego_to_cam(xyz_ego, calib.left_to_ego)

    # --- depth filter ---
    depth_mask = (xyz_cam[:, 2] >= cfg.min_depth_m) & (xyz_cam[:, 2]
                                                       <= cfg.max_depth_m)
    xyz_cam = xyz_cam[depth_mask]
    xyz_ego = xyz_ego[depth_mask]

    # --- project & image-box filter ---
    K = calib.left_intrinsics.astype(np.float32)
    uv, valid = _project_to_image(xyz_cam, K, img_w, img_h)
    in_box = (valid
              & (uv[:, 0] >= x1) & (uv[:, 0] <= x2)
              & (uv[:, 1] >= y1) & (uv[:, 1] <= y2))
    if not in_box.any():
        return np.zeros((0, D), dtype=np.float32)

    pts_cam = xyz_cam[in_box]  # (M, 3) camera frame
    uv_sel = uv[in_box]  # (M, 2) pixel coords

    # --- optional frustum-local rotation ---
    if cfg.frustum_frame:
        centroid_dir = pts_cam.mean(axis=0)
        centroid_dir /= (np.linalg.norm(centroid_dir) + 1e-9)
        z_axis = np.array([0.0, 0.0, 1.0], dtype=np.float32)
        v = np.cross(centroid_dir, z_axis)
        s = np.linalg.norm(v)
        c = float(np.dot(centroid_dir, z_axis))
        if s > 1e-6:
            vx = np.array(
                [[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]],
                dtype=np.float32)
            R = np.eye(3, dtype=np.float32) + vx + vx @ vx * ((1 - c) /
                                                              (s * s))
        else:
            R = np.eye(
                3, dtype=np.float32) if c > 0 else -np.eye(3, dtype=np.float32)
        pts_cam = (R @ pts_cam.T).T

    # --- depth normalisation ---
    if cfg.depth_normalise:
        z_min, z_max = pts_cam[:, 2].min(), pts_cam[:, 2].max()
        dz = z_max - z_min if z_max > z_min else 1.0
        pts_cam = pts_cam.copy()
        pts_cam[:, 2] = (pts_cam[:, 2] - z_min) / dz

    # --- append RGB ---
    if cfg.append_rgb:
        u_idx = np.clip(np.round(uv_sel[:, 0]).astype(np.int32), 0, img_w - 1)
        v_idx = np.clip(np.round(uv_sel[:, 1]).astype(np.int32), 0, img_h - 1)
        rgb = sample.image_left[v_idx, u_idx].astype(np.float32) / 255.0
        return np.hstack([pts_cam, rgb])  # (M, 6)

    return pts_cam  # (M, 3)


# ===========================================================================
# 3.  Voxels
# ===========================================================================
@dataclass
class VoxelConfig:
    """Configuration for :func:`voxel_grid`."""
    x_range: tuple[float, float] = (-40.0, 40.0)
    y_range: tuple[float, float] = (-40.0, 40.0)
    z_range: tuple[float, float] = (-3.0, 1.0)
    voxel_size: float = 0.2  # metres per voxel (isotropic)
    #: Channels per voxel:
    #:  0 – binary occupancy
    #:  1 – mean height (normalised)
    #:  2 – point count (log1p-normalised)
    #:  3 – mean intensity (if available)
    num_channels: int = 4
    max_points_per_voxel: int = 35  # cap for mean-feature computation


@dataclass
class VoxelGrid:
    """Output of :func:`voxel_grid`."""
    features: np.ndarray  # (C, D, H, W) float32
    coords: np.ndarray  # (N_occupied, 3) int32  (d, h, w) indices
    config: VoxelConfig


def voxel_grid(
    sample: StereoSample,
    config: VoxelConfig | None = None,
) -> VoxelGrid:
    """Build a volumetric feature grid from the ego-frame point cloud.

    :param sample: A :class:`~data.StereoSample`.
    :param config: :class:`VoxelConfig`; uses defaults when ``None``.
    :returns: :class:`VoxelGrid` with ``features`` shaped ``(C, D, H, W)``.
    """
    cfg = config or VoxelConfig()
    vs = cfg.voxel_size

    D = int(round((cfg.z_range[1] - cfg.z_range[0]) / vs))
    H = int(round((cfg.y_range[1] - cfg.y_range[0]) / vs))
    W = int(round((cfg.x_range[1] - cfg.x_range[0]) / vs))

    empty_coords = np.zeros((0, 3), dtype=np.int32)
    empty_feat = np.zeros((cfg.num_channels, D, H, W), dtype=np.float32)

    xyz = sample.lidar_xyz.astype(np.float32)
    if xyz.shape[0] == 0:
        return VoxelGrid(features=empty_feat, coords=empty_coords, config=cfg)

    # --- spatial filter ---
    mask = ((xyz[:, 0] >= cfg.x_range[0]) & (xyz[:, 0] < cfg.x_range[1])
            & (xyz[:, 1] >= cfg.y_range[0]) & (xyz[:, 1] < cfg.y_range[1])
            & (xyz[:, 2] >= cfg.z_range[0]) & (xyz[:, 2] < cfg.z_range[1]))
    xyz = xyz[mask]

    intensity: np.ndarray | None = None
    if sample.lidar_features is not None and cfg.num_channels >= 4:
        for key in ("intensity", "reflectance"):
            if key in sample.lidar_features:
                intensity = sample.lidar_features[key].astype(np.float32)[mask]
                break

    # --- voxel indices ---
    ix = np.floor(
        (xyz[:, 0] - cfg.x_range[0]) / vs).astype(np.int32).clip(0, W - 1)
    iy = np.floor(
        (xyz[:, 1] - cfg.y_range[0]) / vs).astype(np.int32).clip(0, H - 1)
    iz = np.floor(
        (xyz[:, 2] - cfg.z_range[0]) / vs).astype(np.int32).clip(0, D - 1)

    feat = np.zeros((cfg.num_channels, D, H, W), dtype=np.float32)

    # Channel 0: occupancy
    feat[0, iz, iy, ix] = 1.0

    # Channel 1: mean height (normalised)
    z_norm = ((xyz[:, 2] - cfg.z_range[0]) /
              (cfg.z_range[1] - cfg.z_range[0])).clip(0.0, 1.0)
    count = np.zeros((D, H, W), dtype=np.float32)
    np.add.at(count, (iz, iy, ix), 1.0)
    np.add.at(feat[1], (iz, iy, ix), z_norm)
    occ_mask = count > 0
    feat[1, occ_mask] /= count[occ_mask]

    # Channel 2: log density
    max_c = count.max() if count.max() > 0 else 1.0
    feat[2] = np.log1p(count) / np.log1p(max_c)

    # Channel 3: mean intensity
    if intensity is not None and cfg.num_channels >= 4:
        np.add.at(feat[3], (iz, iy, ix), intensity)
        feat[3, occ_mask] /= count[occ_mask]
        peak = feat[3].max()
        if peak > 0:
            feat[3] /= peak

    occupied_dhw = np.stack(np.where(feat[0] > 0), axis=1).astype(np.int32)
    return VoxelGrid(features=feat, coords=occupied_dhw, config=cfg)


# ===========================================================================
# 4.  Clustering (DBSCAN)
# ===========================================================================
@dataclass
class ClusterConfig:
    """Configuration for :func:`cluster_points`."""
    eps_m: float = 0.5  # DBSCAN neighbourhood radius (metres)
    min_samples: int = 5  # minimum cluster size
    use_bev: bool = True  # cluster in 2-D (XY) instead of 3-D XYZ
    #: If True, cluster only background returns (points_outside_boxes_xyz).
    background_only: bool = False
    z_range: tuple[float, float] = (-3.0, 1.0)  # height pre-filter


@dataclass
class ClusterStats:
    """Per-cluster statistics returned by :func:`cluster_points`."""
    label: int  # cluster id (0-based; -1 = noise)
    num_points: int
    centroid: np.ndarray  # (3,) ego-frame XYZ
    extent: np.ndarray  # (3,) axis-aligned bounding box extents (L,W,H)
    bbox_min: np.ndarray  # (3,) AABB minimum corner
    bbox_max: np.ndarray  # (3,) AABB maximum corner


def _dbscan(pts: np.ndarray, eps: float, min_samples: int) -> np.ndarray:
    """Pure-numpy DBSCAN via a KD-tree (no sklearn dependency).

    :param pts:         ``(P, d)`` float array of points.
    :param eps:         Neighbourhood radius.
    :param min_samples: Minimum neighbours (inclusive of the point itself).
    :returns:           Integer label array of length P. ``-1`` = noise.
    """
    P = pts.shape[0]
    labels = np.full(P, -1, dtype=np.int32)
    visited = np.zeros(P, dtype=bool)
    tree = cKDTree(pts)

    cluster_id = 0
    for i in range(P):
        if visited[i]:
            continue
        visited[i] = True
        neighbours = tree.query_ball_point(pts[i], eps)
        if len(neighbours) < min_samples:
            continue  # noise (label stays -1)
        labels[i] = cluster_id
        queue = list(neighbours)
        while queue:
            j = queue.pop()
            if not visited[j]:
                visited[j] = True
                nn_j = tree.query_ball_point(pts[j], eps)
                if len(nn_j) >= min_samples:
                    queue.extend(nn_j)
            if labels[j] == -1:
                labels[j] = cluster_id
        cluster_id += 1

    return labels


def cluster_points(
    sample: StereoSample,
    config: ClusterConfig | None = None,
) -> tuple[np.ndarray, list[ClusterStats]]:
    """Cluster LiDAR returns with DBSCAN and return per-point labels + stats.

    :param sample: A :class:`~data.StereoSample`.
    :param config: :class:`ClusterConfig`; uses defaults when ``None``.
    :returns: ``(labels, cluster_stats)`` where ``labels`` is a ``(P,)``
              int32 array aligned with the chosen point set, and
              ``cluster_stats`` is a list of :class:`ClusterStats` (sorted by
              descending point count, noise cluster excluded).
    """
    cfg = config or ClusterConfig()

    xyz_full = (sample.points_outside_boxes_xyz.astype(np.float32) if
                cfg.background_only else sample.lidar_xyz.astype(np.float32))

    if xyz_full.shape[0] == 0:
        return np.zeros(0, dtype=np.int32), []

    # height pre-filter
    z_ok = (xyz_full[:, 2] >= cfg.z_range[0]) & (xyz_full[:, 2]
                                                 <= cfg.z_range[1])
    xyz = xyz_full[z_ok]

    if xyz.shape[0] == 0:
        labels_out = np.full(xyz_full.shape[0], -1, dtype=np.int32)
        return labels_out, []

    pts_for_cluster = xyz[:, :2] if cfg.use_bev else xyz
    labels_filtered = _dbscan(pts_for_cluster, cfg.eps_m, cfg.min_samples)

    # map back to original indexing
    labels_out = np.full(xyz_full.shape[0], -1, dtype=np.int32)
    labels_out[z_ok] = labels_filtered

    # --- per-cluster statistics ---
    unique_labels = sorted(set(labels_filtered.tolist()) - {-1})
    stats: list[ClusterStats] = []
    for lbl in unique_labels:
        pts_lbl = xyz[labels_filtered == lbl]
        centroid = pts_lbl.mean(axis=0)
        bbox_min = pts_lbl.min(axis=0)
        bbox_max = pts_lbl.max(axis=0)
        extent = bbox_max - bbox_min
        stats.append(
            ClusterStats(
                label=lbl,
                num_points=len(pts_lbl),
                centroid=centroid,
                extent=extent,
                bbox_min=bbox_min,
                bbox_max=bbox_max,
            ))
    stats.sort(key=lambda s: s.num_points, reverse=True)
    return labels_out, stats


# ===========================================================================
# Demo
# ===========================================================================
if __name__ == "__main__":

    sample = Py123dDataset(
        split_names=[G.TRAIN_SPLIT])[0].to_stereo_sample()
    print(dir(sample))
    sd = stereo_depth(sample)
    bev = stereo_bev(sample)

    d = sd.depth[sd.depth > 0]
    print(f"Frame      : {sample.dataset}  iter={sample.iteration}")
    print(
        f"Rect size  : {sd.rect.size}  fx_rect={sd.rect.fx_rect:.1f}  base={sd.rect.baseline_m:.4f} m"
    )
    print(f"Disparity  : valid={float((sd.disparity > 0).mean())*100:.1f}%")
    print(f"Depth      : valid={float((sd.depth > 0).mean())*100:.1f}%  "
          f"min={d.min():.1f} med={np.median(d):.1f} max={d.max():.1f} m")
    xyz, _ = stereo_point_cloud(sample)
    print(f"Point cloud: {xyz.shape[0]} ego-frame points")
    print(
        f"Stereo BEV : {bev.shape}  occupancy={float(bev[0].mean())*100:.1f}% cells"
    )
